-- 2026-07-08 — LinkedIn post approval loop
-- Backs the "LinkedIn Post Generator" + "LinkedIn Post Approval Handler" workflows.
-- AI drafts a broadcast LinkedIn post -> human approves via HMAC link -> a rep posts it
-- manually (track-only; the pipeline never auto-posts). Internal only — anon/authenticated
-- revoked (the default-ACL leak would otherwise grant them CRUD on this new table).

create table if not exists linkedin_posts (
  id bigint primary key generated by default as identity,
  account text,
  topic text,
  post_body text not null,
  tracked_url text,
  status text not null default 'pending_approval',  -- pending_approval | approved | rejected | posted
  rejection_reason text,
  posted_url text,                                    -- optional: live post URL, logged back after posting
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  posted_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

revoke all on linkedin_posts from anon, authenticated;

comment on table linkedin_posts is
  'AI-drafted LinkedIn posts pending human approval before a rep posts them manually. status: pending_approval|approved|rejected|posted. Internal only. Added 2026-07-08.';
