-- ============================================================
-- DP Syntropy — Supabase schema (pipeline + dashboard)
-- Project: fqsqoxsosavjhdsvfevk  (region ap-southeast-2)
-- Generated from live DB. Run against a fresh Postgres/Supabase
-- project to reproduce tables, views, and config access.
-- ============================================================

-- ---------- Core tables ----------

create table if not exists pipeline_runs (
  id integer primary key generated by default as identity,
  run_at timestamptz default now(),
  company text,
  trigger_type text,
  is_actionable boolean,
  coverage_label text,
  engaged_count integer,
  total_count integer,
  gate1_score integer,
  gate1_threshold integer,
  gate1_confidence text,
  gate1_rationale text,
  gate1_vetoed boolean,
  gate1_veto_reason text,
  gate1_result text,
  gate2_result text,
  brief_generated boolean,
  brief_s3_url text,
  human_approved boolean,
  notes text,
  when_urgency text,
  when_stage text,
  cap_archetype text,
  cap_confidence text,
  source text,
  raw_payload text,          -- original WHEN-layer brief JSON (for rejection echo)
  industry text,             -- segmentation
  theme text,                -- segmentation
  trigger_notes text,        -- segmentation (WHEN change_triggers.notes)
  enrichment_needed boolean  -- buying group has unconfirmed contacts
);

create table if not exists actions (
  id bigint primary key generated by default as identity,
  run_id integer references pipeline_runs(id),
  account text,
  action_type text,
  hypothesis text,
  predicted_metric text,
  predicted_direction text default 'increase' not null,
  threshold numeric,
  window_days integer default 14 not null,
  utm_campaign text,
  status text default 'recommended' not null,  -- recommended | executed | measured | cancelled
  created_at timestamptz default now() not null,
  executed_at timestamptz,
  tracked_url text,
  rejection_reason text,
  rejection_routed_to text,  -- source | engine_logic
  decided_at timestamptz,
  outreach_draft text,       -- WHEN engine's ready-made outreach copy
  target text,                -- contact/asset the action is aimed at
  priority integer,           -- lower = higher priority; carries cadence_steps.step_number when promoted from a campaign
  reason text,                -- why this action, in plain language
  campaign_id bigint,         -- FK to campaigns(id), added below once that table exists
  salesforce_task_id text,    -- Salesforce Task Id, if/when per-action Task sync is built; reserved, unpopulated for now
  -- Channel recommendation AI (2026-06-29, Phase 5) — see cadence_steps below for details.
  channel_source text default 'template' not null,  -- 'ai' | 'template'
  channel_reco_reason text                          -- AI's stated reason for this channel/step, null when channel_source='template'
);

create table if not exists outcomes (
  id bigint primary key generated by default as identity,
  action_id bigint references actions(id),
  measured_metric text,
  measured_value numeric,
  baseline_value numeric,
  effect numeric,
  result text,               -- met | not_met
  source text,               -- ga4 | gmail
  window_start timestamptz,
  window_end timestamptz,
  measured_at timestamptz default now(),
  notes text
);

create table if not exists pipeline_errors (
  id integer primary key generated by default as identity,
  occurred_at timestamptz default now(),
  company text,
  phase text,
  node_name text,
  error_msg text,
  resolved boolean default false
);

-- Raw engagement events (feeds attribution + channel-performance views)
create table if not exists engagement_events (
  id bigint primary key generated by default as identity,
  account text,
  contact text,
  source text,
  event_type text,           -- email_open | email_click | ad_click | page_visit | reply | meeting_booked | stage_change | form_fill
  campaign text,
  action_id bigint,
  value numeric,
  occurred_at timestamptz,
  metadata jsonb default '{}'::jsonb,
  ingested_at timestamptz default now(),
  forwarded boolean default false not null,  -- set by "Engagement → WHEN Signals" once forwarded upstream
  -- Salesforce Activities read-back (2026-06-30) — dedup key for activity rows
  -- inserted by the "Salesforce Activities Read-back" workflow (event_type
  -- 'crm_activity', source 'salesforce'). Null for every other source/type.
  salesforce_activity_id text
);

-- Salesforce Leads this pipeline has created or matched (2026-06-30) — the
-- "store the Salesforce ID, then read against it" mapping table that the
-- Salesforce Activities Read-back workflow queries daily. Populated by
-- Action Approval Handler's "Record Lead Mapping (Existing)"/"(New)" nodes
-- on its existing Lead-sync branch.
create table if not exists salesforce_leads (
  id bigint primary key generated by default as identity,
  account text not null,
  contact_name text not null,
  salesforce_lead_id text not null unique,
  campaign_id bigint references campaigns(id),
  created_at timestamptz default now()
);

-- ---------- Campaigns & cadences (multi-step outreach on top of actions) ----------

create table if not exists campaigns (
  id bigint primary key generated by default as identity,
  run_id integer references pipeline_runs(id),
  account text,
  status text default 'active' not null,  -- active | completed | cancelled
  created_at timestamptz default now(),
  -- Salesforce sync (2026-06-28) — Supabase stays the system of record; these
  -- columns track a one-way push to a Salesforce Campaign created via n8n's
  -- customObject create/update/delete trio (works against standard objects,
  -- not just true __c custom objects). See n8n-workflows/README.md.
  salesforce_campaign_id text,           -- Salesforce Campaign Id (701...), null until synced
  salesforce_sync_status text default 'pending' not null,  -- pending | synced | error | skipped
  salesforce_synced_at timestamptz,
  salesforce_sync_error text,
  -- Campaign templates (2026-06-28) — key of the campaign_templates row that
  -- "Select Campaign Template" matched at creation time; the matched
  -- template's `steps` became this campaign's cadence_steps.
  template_key text,
  -- Template-selection audit trail (2026-06-30) — full output of "Select
  -- Campaign Template"'s ranked match query at creation time: which template
  -- won, its priority, and every runner-up that also matched, with the
  -- reason the winner was picked. template_key above stays the simple
  -- "what we picked" column; this is "why", for the Account 360 dashboard.
  template_match_trace jsonb,
  -- Adaptive Decision Engine (2026-06-29, Phase 4) — why automation (rather
  -- than a human) moved this campaign to its current status, e.g. 'goal_met'
  -- when a measured outcome satisfied the campaign's goal early.
  completion_reason text,
  -- Salesforce Opportunity creation, human-gated (2026-06-30) — a goal_met
  -- campaign is offered to a human via an HMAC-signed email link (Opportunity
  -- Offer workflow); approving creates a real sandbox-org Opportunity
  -- (Opportunity Approval Handler). not_offered -> offered -> created|declined|error.
  opportunity_status text default 'not_offered' not null,
  opportunity_offered_at timestamptz,
  opportunity_created_at timestamptz,
  opportunity_error text,
  salesforce_opportunity_id text,
  constraint campaigns_salesforce_sync_status_check
    check (salesforce_sync_status = any (array['pending'::text, 'synced'::text, 'error'::text, 'skipped'::text])),
  constraint campaigns_opportunity_status_check
    check (opportunity_status = any (array['not_offered'::text, 'offered'::text, 'created'::text, 'declined'::text, 'error'::text]))
);

create table if not exists cadence_steps (
  id bigint primary key generated by default as identity,
  campaign_id bigint references campaigns(id),
  account text,
  step_number integer,
  delay_days integer default 0 not null,      -- days after campaign creation this step is due
  scheduled_for timestamptz,
  action_type text,
  target text,
  reason text,
  hypothesis text,
  predicted_metric text,
  predicted_direction text,
  threshold numeric,
  window_days integer,
  utm_campaign text,
  tracked_url text,
  outreach_draft text,
  status text default 'pending' not null,     -- pending | recommended | executed | measured | cancelled | skipped
  action_id bigint references actions(id),    -- set once Cadence Scheduler promotes this step to a real action
  created_at timestamptz default now(),
  -- Channel recommendation AI (2026-06-29, Phase 5) — "Channel Recommendation AI"
  -- (Brief Approval Handler) replaces the matched campaign_templates row's default
  -- steps with an LLM-recommended channel sequence built from account score, prior
  -- actions, channel performance, buying-group role/confirmation, and the template's
  -- own steps as a starting point. channel_source records which one actually won:
  -- 'ai' when the model returned a valid plan, 'template' on fallback (AI error, or
  -- output that fails JSON/vocabulary/range validation in "Parse AI Channel Plan").
  -- channel_reco_reason carries the AI's stated reason per step; null on fallback.
  channel_source text default 'template' not null,  -- 'ai' | 'template'
  channel_reco_reason text,
  -- Adaptive Decision Engine (2026-06-29, Phase 4) — set by the "Adaptive
  -- Decision Engine" workflow once the originating outcome is measured:
  -- 'escalated' (bumped to a higher-touch channel), 'paused' (scheduled_for
  -- pushed out due to zero engagement), 'stopped' (cancelled because the
  -- campaign goal was met elsewhere), 'reviewed' (no adaptive action
  -- needed), or null if not yet evaluated. The source query filters on
  -- adaptive_action is null, so this also makes the workflow idempotent —
  -- no separate "already processed" tracking table needed.
  adaptive_action text,
  adaptive_reason text
);

-- actions.campaign_id FK, deferred until campaigns exists
alter table actions add constraint actions_campaign_id_fkey
  foreign key (campaign_id) references campaigns(id);

-- Mirror an action's status back onto the cadence_steps row it came from,
-- so the existing approve/reject flow (which only ever updates `actions`)
-- keeps the cadence view in sync without any new approval-handler logic.
create or replace function sync_cadence_step_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  if new.status is distinct from old.status then
    update cadence_steps set status = new.status where action_id = new.id;
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_sync_cadence_step_status on actions;
create trigger trg_sync_cadence_step_status
  after update on actions
  for each row execute function sync_cadence_step_status();

-- ---------- Campaign template library (auto-matched cadences) ----------
-- "Select Campaign Template" (Brief Approval Handler) runs a priority-ordered
-- match against this table using the approved brief's when_urgency /
-- coverage_label / when_stage / trigger_type (NULL match_* column = wildcard
-- on that dimension; lowest `priority` wins). The matched row's `steps`
-- (action_type / delay_days / reason, in order) becomes the campaign's
-- cadence. `warm_reengage` (priority 99, every match_* column NULL) is the
-- catch-all fallback. Selection is fully automatic — no manual picker.
create table if not exists campaign_templates (
  id bigint primary key generated by default as identity,
  key text not null unique,
  name text not null,
  description text,
  match_urgency_in text[],       -- NULL = wildcard; else upper(when_urgency) must be in this array
  match_coverage_in text[],      -- NULL = wildcard; else upper(coverage_label) must be in this array
  match_stage_contains text,     -- NULL = wildcard; else upper(when_stage) ILIKE '%...%' this value
  priority integer not null,     -- lower wins; first match by this order is selected
  steps jsonb not null,          -- [{ action_type, delay_days, reason }, ...] in cadence order
  created_at timestamptz not null default now(),
  match_keywords text[],         -- NULL = wildcard; else trigger_type ILIKE '%keyword%' for any keyword
  goal text,                     -- plain-language objective of this template
  kpi_metric text,               -- the metric this template is judged against
  kpi_target text                -- target threshold/timeframe for kpi_metric
);

-- Seed the 15 named templates (18 rows incl. priority-tier variants), in
-- priority order. action_type values map to channels via the META table in
-- "Recommend Action" (Brief Approval Handler): linkedin_connect, linkedin_engage,
-- email, invite, landing_page, content_download, ads, webinar, phone, partner.
insert into campaign_templates (key, name, priority, match_urgency_in, match_coverage_in, match_stage_contains, match_keywords, steps, goal, kpi_metric, kpi_target, description) values
('urgent_fast_track', 'Urgent fast-track', 10,
  ARRAY['URGENT','LIVE','HIGH','ACT NOW'], NULL, NULL, NULL,
  '[{"action_type":"email","reason":"Lead with the urgency signal — do not wait","delay_days":0},
    {"action_type":"landing_page","reason":"Drive to a tailored account page while it is hot","delay_days":1},
    {"action_type":"invite","reason":"Ask for the meeting directly — urgency justifies skipping content gating","delay_days":3}]'::jsonb,
  'Move fast on a time-sensitive, high-urgency signal before the window closes', 'reply_or_meeting', '1 response within 7 days',
  'High-urgency signal — skip the slow build, go straight for the ask.'),

('competitive_replacement', 'Competitive Replacement', 11,
  NULL, NULL, NULL, ARRAY['competitor','displace','displacement','rival','switch from','incumbent','rip and replace'],
  '[{"action_type":"email","reason":"Open with the competitive displacement angle — name the gap in their current vendor and a concrete head-to-head comparison.","delay_days":0},
    {"action_type":"linkedin_engage","reason":"Engage with their recent activity to stay visible while the comparison lands.","delay_days":2},
    {"action_type":"content_download","reason":"Send the competitive comparison sheet.","delay_days":4},
    {"action_type":"phone","reason":"Call to push for a meeting before they renew with the incumbent.","delay_days":7},
    {"action_type":"email","reason":"Final follow-up referencing the comparison sheet and a renewal-timeline question.","delay_days":10}]'::jsonb,
  'Win a head-to-head displacement before the incumbent renews', 'reply_or_meeting', '1 meeting booked within 14 days',
  'Account is actively evaluating or being approached about replacing an incumbent vendor.'),

('executive_event', 'Executive Event / Leadership Change', 12,
  NULL, NULL, NULL, ARRAY['leadership change','new ceo','new cto','new cfo','new coo','executive appointment','interim appointed','executive change'],
  '[{"action_type":"linkedin_connect","reason":"Connect with the new executive directly.","delay_days":0},
    {"action_type":"email","reason":"Congratulate on the new role and tie our catch to their likely first-90-days priorities.","delay_days":3},
    {"action_type":"linkedin_engage","reason":"Stay visible while they settle into the role.","delay_days":6},
    {"action_type":"phone","reason":"Call to get on the calendar before their plan is finalized.","delay_days":10},
    {"action_type":"email","reason":"Final nudge referencing any public statements they have made since starting.","delay_days":14}]'::jsonb,
  'Build a relationship with the new executive before their first-90-days plan is set', 'reply_or_meeting', '1 meeting booked within 21 days',
  'A new executive has joined or a leadership change creates a fresh window of opportunity.'),

('product_launch', 'Product Launch', 13,
  NULL, NULL, NULL, ARRAY['product launch','launched','new platform','platform announc','unveil','rollout','go-live','go live'],
  '[{"action_type":"email","reason":"Congratulate on the launch and connect our capability to what they just shipped.","delay_days":0},
    {"action_type":"linkedin_engage","reason":"Engage with their launch announcement post.","delay_days":2},
    {"action_type":"content_download","reason":"Share a relevant case study or technical brief.","delay_days":5},
    {"action_type":"email","reason":"Follow up before the next vendor evaluation cycle starts.","delay_days":9}]'::jsonb,
  'Land early before competitors pile onto the new initiative', 'reply_or_meeting', '1 meeting booked within 14 days',
  'Account just launched a new product, platform, or initiative.'),

('partner_campaign', 'Partner Campaign', 14,
  NULL, NULL, NULL, ARRAY['partner','partnership','alliance','co-sell','collaboration'],
  '[{"action_type":"partner","reason":"Loop in our partner contact to make a warm introduction off the back of the announced partnership.","delay_days":0},
    {"action_type":"email","reason":"Follow the partner intro with a direct note tying our offering to the partnership.","delay_days":3},
    {"action_type":"linkedin_connect","reason":"Connect directly in parallel with the partner-led intro.","delay_days":5},
    {"action_type":"phone","reason":"Call to convert the warm intro into a meeting.","delay_days":9}]'::jsonb,
  'Open a co-sell or ecosystem conversation off the back of the partnership announcement', 'partner_response', '1 partner-side response within 14 days',
  'Account has an active or newly announced partnership/alliance we can route through.'),

('narrow_coverage_nurture', 'Narrow-coverage nurture', 15,
  NULL, ARRAY['NARROW'], NULL, NULL,
  '[{"action_type":"content_download","reason":"Offer a gated asset — no confirmed contact to message directly yet","delay_days":0},
    {"action_type":"landing_page","reason":"Drive traffic while enrichment is pending","delay_days":4},
    {"action_type":"linkedin_connect","reason":"Attempt to confirm a real contact via connect","delay_days":8},
    {"action_type":"email","reason":"Only once some signal suggests a contact is reachable","delay_days":14}]'::jsonb,
  'Build buying-group coverage on a narrowly-covered account before pushing for a meeting', 'profile_visit', 'expand confirmed contacts to 2+ within 21 days',
  'Buying group contacts are unconfirmed — lower-touch, content/ad-led cadence per the coverage-routing rule.'),

('conference_followup', 'Conference Follow-up', 16,
  NULL, NULL, NULL, ARRAY['conference','summit','expo','trade show','booth','attended'],
  '[{"action_type":"email","reason":"Reference the specific conversation or booth visit while it is still fresh.","delay_days":0},
    {"action_type":"linkedin_connect","reason":"Connect on LinkedIn right after the event.","delay_days":1},
    {"action_type":"content_download","reason":"Send the resource they asked about at the event.","delay_days":3},
    {"action_type":"phone","reason":"Call to lock in a follow-up meeting before the post-event window closes.","delay_days":5}]'::jsonb,
  'Convert a fresh event touchpoint into a meeting while the conversation is still warm', 'reply_or_meeting', '1 meeting booked within 7 days',
  'Account was sourced from or engaged at a conference, summit, or trade show.'),

('webinar', 'Webinar', 17,
  NULL, NULL, NULL, ARRAY['webinar','registered for','signed up for','online event'],
  '[{"action_type":"webinar","reason":"Invite to the related or next webinar session, or send the recording.","delay_days":0},
    {"action_type":"email","reason":"Follow up on what they registered for and offer a related resource.","delay_days":2},
    {"action_type":"linkedin_engage","reason":"Engage with their profile to stay visible.","delay_days":4},
    {"action_type":"content_download","reason":"Share related content to keep them engaged toward a meeting.","delay_days":7}]'::jsonb,
  'Turn a webinar registration into a qualified follow-on conversation', 'registration', '1 follow-on meeting within 10 days',
  'Account registered for or attended a webinar.'),

('abm', 'ABM (Named Account, Broad Coverage)', 18,
  NULL, ARRAY['BROAD'], NULL, NULL,
  '[{"action_type":"linkedin_connect","reason":"Connect with each confirmed buying-group member in parallel.","delay_days":0},
    {"action_type":"email","reason":"Send a tailored note to the primary stakeholder.","delay_days":2},
    {"action_type":"linkedin_engage","reason":"Engage across the buying group to stay visible to all threads.","delay_days":5},
    {"action_type":"ads","reason":"Run account-targeted retargeting while multi-threading the buying group.","delay_days":7},
    {"action_type":"phone","reason":"Call the primary stakeholder to consolidate the multi-thread into a meeting.","delay_days":10},
    {"action_type":"email","reason":"Recap with the full buying group and propose next steps.","delay_days":16}]'::jsonb,
  'Multi-thread the full buying group on a named account before single-threaded competitors do', 'reply_or_meeting', '2+ stakeholder replies within 21 days',
  'Full buying-group coverage on a named account — multi-thread rather than single-thread.'),

('cold_outreach', 'Cold outreach', 20,
  NULL, NULL, 'COLD', NULL,
  '[{"action_type":"linkedin_connect","reason":"Lowest-friction first touch — open the relationship","delay_days":0},
    {"action_type":"linkedin_engage","reason":"Warm them via likes/comments on recent posts","delay_days":2},
    {"action_type":"email","reason":"Lead with the strategic angle","delay_days":5},
    {"action_type":"content_download","reason":"Offer a gated asset to gauge intent","delay_days":7},
    {"action_type":"invite","reason":"Easier ask than a sales call","delay_days":10}]'::jsonb,
  'Establish initial contact and qualify interest on a cold-stage account', 'reply_or_meeting', '1 response within 21 days',
  'Cold-stage account — open the relationship gradually before asking for anything.'),

('cross_sell', 'Cross-Sell', 21,
  NULL, NULL, NULL, ARRAY['cross-sell','cross sell','also use','adjacent product','additional license'],
  '[{"action_type":"email","reason":"Introduce the adjacent product line relevant to their current usage.","delay_days":0},
    {"action_type":"linkedin_engage","reason":"Stay visible while they consider the adjacent offering.","delay_days":4},
    {"action_type":"content_download","reason":"Share a case study on the adjacent product.","delay_days":7},
    {"action_type":"phone","reason":"Call to scope a cross-sell conversation.","delay_days":12}]'::jsonb,
  'Expand footprint into an adjacent product line within an existing account', 'reply_or_meeting', '1 meeting booked within 21 days',
  'Existing account showing signals for an adjacent product line.'),

('renewal', 'Renewal', 22,
  NULL, NULL, NULL, ARRAY['renewal','contract expir','up for renewal','renew'],
  '[{"action_type":"email","reason":"Open the renewal conversation early, ahead of the contract end date.","delay_days":0},
    {"action_type":"phone","reason":"Call to confirm renewal intent and surface any risk.","delay_days":5},
    {"action_type":"linkedin_engage","reason":"Stay visible through the renewal cycle.","delay_days":8},
    {"action_type":"email","reason":"Follow up with renewal terms or an expansion option.","delay_days":14}]'::jsonb,
  'Lock the renewal early and head off any churn risk', 'reply_or_meeting', '1 meeting booked within 30 days of contract end',
  'Existing account approaching contract renewal.'),

('expansion', 'Expansion', 23,
  NULL, NULL, NULL, ARRAY['expansion','expand usage','scale up','additional seats','growing usage'],
  '[{"action_type":"email","reason":"Flag the usage growth and propose an expanded plan.","delay_days":0},
    {"action_type":"linkedin_engage","reason":"Stay visible while they consider expanding.","delay_days":3},
    {"action_type":"phone","reason":"Call to scope the expansion.","delay_days":7}]'::jsonb,
  'Grow seat count or usage within an already-engaged account', 'reply_or_meeting', '1 meeting booked within 21 days',
  'Existing account showing usage growth signals worth expanding.'),

('customer_success', 'Customer Success Check-in', 24,
  NULL, NULL, NULL, ARRAY['customer success','health check','renewal risk','low adoption','onboarding'],
  '[{"action_type":"email","reason":"Proactively check in on the adoption or health signal.","delay_days":0},
    {"action_type":"phone","reason":"Call to understand the root cause and offer help.","delay_days":3},
    {"action_type":"linkedin_engage","reason":"Stay visible during the check-in period.","delay_days":6}]'::jsonb,
  'Proactively address an adoption or health-risk signal before it becomes churn', 'reply_or_meeting', '1 meeting booked within 14 days',
  'Existing account with an adoption or health-risk signal worth a proactive touch.'),

('dormant_account', 'Dormant Account', 30,
  NULL, NULL, NULL, ARRAY['dormant','gone quiet','previously engaged','no recent activity'],
  '[{"action_type":"email","reason":"Light-touch check-in referencing the prior engagement.","delay_days":0},
    {"action_type":"linkedin_engage","reason":"Re-engage gently on LinkedIn.","delay_days":5},
    {"action_type":"content_download","reason":"Share new content relevant to what they cared about before.","delay_days":10}]'::jsonb,
  'Surface a previously-engaged account that has gone quiet before writing them off', 'reply_or_meeting', '1 response within 21 days',
  'Previously-engaged account that has gone quiet.'),

('reactivation', 'Reactivation', 31,
  NULL, NULL, NULL, ARRAY['reactivat','win-back','win back','lapsed','churned'],
  '[{"action_type":"email","reason":"Make a direct win-back offer.","delay_days":0},
    {"action_type":"phone","reason":"Call to address whatever caused the lapse.","delay_days":4},
    {"action_type":"linkedin_connect","reason":"Reconnect on LinkedIn in parallel.","delay_days":7},
    {"action_type":"email","reason":"Final win-back push with a concrete next step.","delay_days":12}]'::jsonb,
  'Win back a lapsed account with a stronger, more direct offer than a standard nurture', 'reply_or_meeting', '1 meeting booked within 21 days',
  'Lapsed or churned account that needs a stronger win-back push than a standard nurture.'),

('thought_leadership', 'Thought Leadership', 85,
  NULL, NULL, NULL, ARRAY['newsletter','subscribed','content syndication','downloaded','whitepaper signup'],
  '[{"action_type":"content_download","reason":"Lead with educational content matched to their stated interest.","delay_days":0},
    {"action_type":"linkedin_engage","reason":"Stay visible without a hard pitch.","delay_days":5},
    {"action_type":"content_download","reason":"Share a second piece of content to build trust.","delay_days":12},
    {"action_type":"email","reason":"Soft check-in — no hard CTA, just gauge interest.","delay_days":20}]'::jsonb,
  'Nurture a low-intent, early-awareness contact with educational content until they show buying signals', 'content_download', 'sustained content engagement; re-evaluate for a harder CTA after 30 days',
  'Low-intent, early-awareness contact (newsletter/content signup) not yet showing buying signals.'),

('warm_reengage', 'Nurture (Warm Re-engage)', 99,
  NULL, NULL, NULL, NULL,
  '[{"action_type":"linkedin_engage","reason":"Re-engage an already-warm contact","delay_days":0},
    {"action_type":"email","reason":"Go direct for a meeting","delay_days":2},
    {"action_type":"landing_page","reason":"Drive to a tailored account page","delay_days":5},
    {"action_type":"content_download","reason":"Offer a gated asset (e.g. sector guide)","delay_days":7},
    {"action_type":"invite","reason":"Offer a roundtable as a soft next step","delay_days":10}]'::jsonb,
  'Keep a warm-but-not-yet-ready account engaged until a stronger buying signal appears', 'profile_visit', 'sustained engagement; re-evaluate in 30 days',
  'Default cadence for an already-warm, decently-covered account that is not yet ready to buy. Fallback template — matches everything not caught above.')
on conflict (key) do nothing;

-- Company-configurable settings (tracking domain, GA4 property, WHEN engine URL)
create table if not exists app_config (
  key text primary key,
  value text,
  description text,
  updated_at timestamptz not null default now()
);

insert into app_config (key, value, description) values
  ('tracking_base_url', '', 'Your GA4-tagged website that outreach tracking links point to'),
  ('ga4_property_id',  '', 'Your Google Analytics 4 numeric property ID'),
  ('when_engine_url',  '', 'WHEN Engine inbound URL; pipeline rejections are POSTed here')
on conflict (key) do nothing;

-- app_config: readable by anon (dashboard), updatable by anon but ONLY for the
-- two keys the Settings tab actually edits, and only the `value` column.
-- (when_engine_url is deliberately excluded — no UI exposes it, so it should
-- not be anon-writable via a raw PATCH either.)
alter table app_config enable row level security;
drop policy if exists app_config_read_public on app_config;
drop policy if exists app_config_anon_update on app_config;
create policy app_config_read_public on app_config for select to public using (true);
create policy app_config_anon_update on app_config for update to anon
  using (key in ('tracking_base_url', 'ga4_property_id'))
  with check (key in ('tracking_base_url', 'ga4_property_id'));
grant select on app_config to anon, authenticated;
grant update (value) on app_config to anon;

-- ---------- RLS lockdown: default-deny on every base table the anon key can see ----------
-- The anon key is embedded client-side in both dashboard HTML files. Every
-- legitimate read goes through a SECURITY DEFINER view below (the view owner's
-- privileges apply, not anon's, so base-table RLS/grants don't block reads);
-- every legitimate write goes through n8n's Postgres credential, which connects
-- as `postgres` (rolbypassrls = true, unaffected by RLS). So: enable RLS with
-- zero anon/authenticated policies, and revoke any stray grants, on every
-- exposed base table. New tables (campaigns, cadence_steps) follow the same
-- convention from creation.
alter table actions enable row level security;
alter table outcomes enable row level security;
alter table engagement_events enable row level security;
alter table pipeline_runs enable row level security;
alter table pipeline_errors enable row level security;
alter table campaigns enable row level security;
alter table cadence_steps enable row level security;
alter table campaign_templates enable row level security;

revoke all on actions, outcomes, engagement_events, pipeline_runs, pipeline_errors,
  campaigns, cadence_steps, campaign_templates
from anon, authenticated;

-- ---------- Dashboard / console views ----------

create or replace view dashboard_kpis as  SELECT count(*) AS total,
    count(*) FILTER (WHERE gate1_result = 'PASS'::text) AS gate1_pass,
    count(*) FILTER (WHERE gate1_result = 'VETOED'::text) AS gate1_vetoed,
    count(*) FILTER (WHERE gate2_result = 'PASS'::text) AS gate2_pass,
    count(*) FILTER (WHERE brief_generated) AS briefs_generated,
    count(*) FILTER (WHERE human_approved) AS approved,
    count(*) FILTER (WHERE gate1_result = 'FAIL'::text AND gate2_result = 'PASS'::text) AS mismatch
   FROM pipeline_runs;

create or replace view dashboard_coverage as  SELECT COALESCE(coverage_label, 'Unknown'::text) AS label,
    count(*) AS n FROM pipeline_runs GROUP BY (COALESCE(coverage_label, 'Unknown'::text));

create or replace view dashboard_trigger_type as  SELECT
        CASE WHEN trigger_type IS NULL OR (TRIM(BOTH FROM trigger_type) = ANY (ARRAY[''::text, ':'::text])) THEN 'Unknown'::text
            ELSE split_part(trigger_type, ':'::text, 1) END AS label,
    count(*) AS n FROM pipeline_runs GROUP BY 1;

create or replace view dashboard_trend as  SELECT date_trunc('day'::text, (run_at AT TIME ZONE 'Asia/Singapore'::text)) AS day,
    count(*) AS n FROM pipeline_runs GROUP BY 1 ORDER BY 1;

create or replace view dashboard_error_health as  SELECT phase, node_name,
    count(*) AS errors, count(*) FILTER (WHERE NOT resolved) AS unresolved
   FROM pipeline_errors GROUP BY phase, node_name;

create or replace view dashboard_action_funnel as  SELECT count(*) AS total,
    count(*) FILTER (WHERE status <> 'cancelled'::text) AS recommended,
    count(*) FILTER (WHERE status = ANY (ARRAY['executed'::text, 'measured'::text])) AS executed,
    count(*) FILTER (WHERE status = 'measured'::text) AS measured,
    count(*) FILTER (WHERE status = 'cancelled'::text) AS cancelled
   FROM actions;

create or replace view dashboard_hypothesis_winrate as  SELECT a.action_type,
    count(o.id) AS measured,
    count(o.id) FILTER (WHERE o.result = 'met'::text) AS met,
    round(100.0 * count(o.id) FILTER (WHERE o.result = 'met'::text)::numeric / NULLIF(count(o.id), 0)::numeric, 0) AS win_rate_pct
   FROM actions a LEFT JOIN outcomes o ON o.action_id = a.id GROUP BY a.action_type;

-- 2026-06-29, Phase 5 follow-up: same shape as dashboard_hypothesis_winrate,
-- grouped by channel_source instead of action_type, so it's ready to answer
-- "did the AI's channel picks actually outperform the template's?" the
-- moment enough actions reach executed/measured to be meaningful (system is
-- still pre-traffic as of this writing — expect empty/near-empty rows).
create or replace view dashboard_channel_source_performance as  SELECT a.channel_source,
    count(*) AS total_actions,
    count(*) FILTER (WHERE a.status = ANY (ARRAY['executed'::text, 'measured'::text])) AS executed,
    count(o.id) AS measured,
    count(o.id) FILTER (WHERE o.result = 'met'::text) AS met,
    round(100.0 * count(o.id) FILTER (WHERE o.result = 'met'::text)::numeric / NULLIF(count(o.id), 0)::numeric, 0) AS win_rate_pct
   FROM actions a LEFT JOIN outcomes o ON o.action_id = a.id GROUP BY a.channel_source;

create or replace view console_pending_briefs as  SELECT id, company, brief_s3_url, when_urgency, when_stage,
    to_char((run_at AT TIME ZONE 'Asia/Singapore'::text), 'MM-DD HH24:MI'::text) AS run_sgt
   FROM pipeline_runs
  WHERE human_approved = false AND brief_generated = true AND COALESCE(notes, ''::text) !~~* '%reject%'::text
  ORDER BY run_at DESC LIMIT 50;

create or replace view console_pending_actions as  SELECT a.id, a.account, a.action_type, a.hypothesis, a.predicted_metric,
    a.tracked_url, a.run_id, p.brief_s3_url, p.when_urgency, p.when_stage, a.created_at
   FROM actions a LEFT JOIN pipeline_runs p ON p.id = a.run_id
  WHERE a.status = 'recommended'::text ORDER BY a.created_at DESC;

-- 2026-06-28: powers quick-log.html's action picker -- "executed" actions
-- (rep has already acted, awaiting a measurable signal), which
-- console_pending_actions (status='recommended' only) doesn't cover.
create or replace view console_open_actions as  SELECT a.id, a.account, a.action_type, a.target, a.predicted_metric,
    a.utm_campaign, a.tracked_url, a.executed_at, a.hypothesis, a.reason
   FROM actions a WHERE a.status = 'executed'::text ORDER BY a.executed_at DESC;

-- 2026-06-28: recent-activity feed under quick-log.html so a manual log
-- shows up immediately as confirmation.
create or replace view console_recent_engagement as  SELECT id, account, event_type, source, campaign,
    action_id, value, occurred_at, metadata, ingested_at
   FROM engagement_events ORDER BY ingested_at DESC;

create or replace view dashboard_rejection_reasons as  SELECT COALESCE(rejection_reason, '(unspecified)'::text) AS label,
    COALESCE(rejection_routed_to, '-'::text) AS routed_to, count(*) AS n
   FROM actions WHERE status = 'cancelled'::text GROUP BY rejection_reason, rejection_routed_to ORDER BY count(*) DESC;

create or replace view dashboard_correction_rate as  SELECT (decided_at AT TIME ZONE 'Asia/Singapore'::text)::date AS cycle,
    count(*) AS decided, count(*) FILTER (WHERE status = 'cancelled'::text) AS corrected,
    round(100.0 * count(*) FILTER (WHERE status = 'cancelled'::text)::numeric / NULLIF(count(*), 0)::numeric, 0) AS correction_rate_pct
   FROM actions WHERE decided_at IS NOT NULL GROUP BY 1 ORDER BY 1;

create or replace view attribution_last_touch as
 WITH conversions AS (SELECT * FROM engagement_events WHERE event_type = ANY (ARRAY['meeting_booked'::text, 'stage_change'::text, 'form_fill'::text])),
      touches AS (SELECT * FROM engagement_events WHERE event_type = ANY (ARRAY['email_click'::text, 'ad_click'::text, 'page_visit'::text, 'reply'::text]))
 SELECT c.id AS conversion_id, c.account, c.event_type AS conversion, c.occurred_at AS converted_at,
    t.campaign AS credited_campaign, t.source AS credited_source, t.occurred_at AS touch_at
   FROM conversions c
     LEFT JOIN LATERAL (SELECT * FROM touches t_1 WHERE t_1.account = c.account AND t_1.occurred_at <= c.occurred_at
          ORDER BY t_1.occurred_at DESC LIMIT 1) t ON true;

create or replace view dashboard_attribution_summary as  SELECT COALESCE(credited_campaign, '(direct/none)'::text) AS campaign,
    COALESCE(credited_source, '(direct/none)'::text) AS source, count(*) AS conversions
   FROM attribution_last_touch GROUP BY 1, 2 ORDER BY count(*) DESC;

create or replace view dashboard_channel_performance as
 WITH touches AS (SELECT source AS channel, count(*) AS touches FROM engagement_events
          WHERE event_type = ANY (ARRAY['email_open'::text, 'email_click'::text, 'ad_click'::text, 'page_visit'::text, 'reply'::text]) GROUP BY source),
      conv AS (SELECT credited_source AS channel, count(*) AS conversions FROM attribution_last_touch
          WHERE credited_source IS NOT NULL GROUP BY credited_source)
 SELECT COALESCE(t.channel, c.channel) AS channel, COALESCE(t.touches, 0::bigint) AS touches,
    COALESCE(c.conversions, 0::bigint) AS conversions,
    round(100.0 * COALESCE(c.conversions, 0::bigint)::numeric / NULLIF(COALESCE(t.touches, 0::bigint), 0)::numeric, 0) AS conv_rate_pct
   FROM touches t FULL JOIN conv c ON t.channel = c.channel ORDER BY 3 DESC, 2 DESC;

-- Segmentation + enrichment
create or replace view dashboard_by_industry as  SELECT COALESCE(NULLIF(industry, ''::text), 'Unknown'::text) AS label,
    count(*) AS n FROM pipeline_runs GROUP BY 1 ORDER BY count(*) DESC;

create or replace view dashboard_by_theme as  SELECT COALESCE(NULLIF(theme, ''::text), 'Unknown'::text) AS label,
    count(*) AS n FROM pipeline_runs GROUP BY 1 ORDER BY count(*) DESC;

create or replace view dashboard_by_trigger as  SELECT COALESCE(NULLIF(trigger_notes, ''::text), 'Unknown'::text) AS label,
    count(*) AS n FROM pipeline_runs GROUP BY 1 ORDER BY count(*) DESC;

create or replace view dashboard_enrichment as  SELECT count(*) FILTER (WHERE enrichment_needed) AS needs_enrichment,
    count(*) FILTER (WHERE enrichment_needed = false) AS enriched, count(*) AS total FROM pipeline_runs;

-- Feedback routing views (rejections). Renamed 2026-06-29 from
-- feedback_for_tabita/feedback_for_engine to drop person-specific naming —
-- six rejection reasons now route to one of two generic destinations,
-- 'source' (a fact/data problem) or 'engine_logic' (a decision problem).
create or replace view feedback_for_source as  SELECT id, account, action_type, rejection_reason, decided_at
   FROM actions WHERE status = 'cancelled'::text AND rejection_routed_to = 'source'::text ORDER BY decided_at DESC;

create or replace view feedback_for_engine_logic as  SELECT id, account, action_type, rejection_reason, decided_at
   FROM actions WHERE status = 'cancelled'::text AND rejection_routed_to = 'engine_logic'::text ORDER BY decided_at DESC;

-- Gate 1 / scoring breakdowns
create or replace view dashboard_gate1_breakdown as  SELECT gate1_result AS label, count(*) AS n
   FROM pipeline_runs GROUP BY gate1_result;

create or replace view dashboard_vetoed_companies as  SELECT company, count(*) AS n
   FROM pipeline_runs WHERE gate1_result = 'VETOED'::text GROUP BY company;

create or replace view dashboard_action_type as  SELECT action_type AS label, count(*) AS n
   FROM actions GROUP BY action_type;

-- Account scoring (engagement-derived + pipeline-derived signal, capped at 100)
-- account_score (rewritten 2026-06-30, items 2 + 4 of the coworker
-- pressure-test gap list):
--   - hard/soft split: event_weights.source IN ('ga4','gmail','salesforce')
--     counts as a "hard" (independently-observed) signal; 'manual' counts as
--     "soft" (self-reported). hard_points/soft_points are exposed alongside
--     the blended `score` so the Channel Recommendation AI (and the Account
--     360 dashboard) can weight hard signals more heavily instead of
--     treating every event type as equally trustworthy.
--   - diminishing returns: occurrence_rank (row_number per account+event_type
--     ordered by occurred_at) caps repeated low-effort events from inflating
--     score without limit — 1st occurrence of a given event_type counts at
--     full weight, 2nd at 0.4x, 3rd+ at 0x. Without this, e.g. 50 page_visit
--     events from one account could outscore a single meeting_booked.
create or replace view account_score as
 WITH event_weights AS (
   SELECT ee.account, ee.source, ee.event_type, ee.occurred_at,
     CASE ee.event_type
       WHEN 'opportunity_created' THEN 50 WHEN 'meeting_booked' THEN 40
       WHEN 'reply_or_meeting' THEN 30
       WHEN 'reply' THEN 20 WHEN 'email_reply' THEN 20 WHEN 'form_fill' THEN 25
       WHEN 'call_connected' THEN 25
       WHEN 'registration' THEN 15
       WHEN 'content_download' THEN 15 WHEN 'stage_change' THEN 15 WHEN 'partner_response' THEN 15
       WHEN 'linkedin_accept' THEN 10 WHEN 'email_click' THEN 5
       WHEN 'email_open' THEN 5 WHEN 'page_visit' THEN 5 WHEN 'profile_visit' THEN 5
       ELSE 2 END AS base_weight,
     row_number() OVER (PARTITION BY ee.account, ee.event_type ORDER BY ee.occurred_at) AS occurrence_rank
   FROM engagement_events ee WHERE ee.account IS NOT NULL
 ), ev AS (
   SELECT event_weights.account,
     sum(event_weights.base_weight::numeric * CASE event_weights.occurrence_rank
       WHEN 1 THEN 1.0 WHEN 2 THEN 0.4 ELSE 0 END) AS event_points,
     sum(event_weights.base_weight::numeric * CASE event_weights.occurrence_rank
       WHEN 1 THEN 1.0 WHEN 2 THEN 0.4 ELSE 0 END)
       FILTER (WHERE event_weights.source = ANY (ARRAY['ga4','gmail','salesforce'])) AS hard_event_points,
     sum(event_weights.base_weight::numeric * CASE event_weights.occurrence_rank
       WHEN 1 THEN 1.0 WHEN 2 THEN 0.4 ELSE 0 END)
       FILTER (WHERE event_weights.source = 'manual') AS soft_points,
     count(*) AS events, max(event_weights.occurred_at) AS last_event
   FROM event_weights
   GROUP BY event_weights.account
 ), base AS (
   SELECT pipeline_runs.company AS account,
     (max(CASE upper(COALESCE(pipeline_runs.coverage_label, ''))
            WHEN 'BROAD' THEN 15 WHEN 'PARTIAL' THEN 10 WHEN 'NARROW' THEN 5 ELSE 0 END)
      + max(CASE WHEN upper(COALESCE(pipeline_runs.when_urgency, '')) = ANY (ARRAY['URGENT','LIVE','HIGH','ACT NOW']) THEN 10 ELSE 0 END)) AS base_points
   FROM pipeline_runs WHERE pipeline_runs.company IS NOT NULL
   GROUP BY pipeline_runs.company
 )
 SELECT COALESCE(ev.account, base.account) AS account,
   LEAST(round((COALESCE(base.base_points, 0)::numeric + COALESCE(ev.event_points, 0))::double precision)::integer, 100) AS score,
   COALESCE(ev.events, 0::bigint) AS engagement_events, ev.last_event,
   round((COALESCE(base.base_points, 0)::numeric + COALESCE(ev.hard_event_points, 0))::double precision)::integer AS hard_points,
   round(COALESCE(ev.soft_points, 0)::double precision)::integer AS soft_points
 FROM ev FULL JOIN base ON ev.account = base.account;

create or replace view dashboard_top_accounts as  SELECT account, score, engagement_events, last_event, hard_points, soft_points
   FROM account_score ORDER BY score DESC, engagement_events DESC LIMIT 15;

-- Account 360 dashboard support views (2026-06-30):
create or replace view dashboard_accounts_list as
 SELECT account, max(last_seen) AS last_seen FROM (
   SELECT pipeline_runs.company AS account, max(pipeline_runs.run_at) AS last_seen
     FROM pipeline_runs WHERE pipeline_runs.company IS NOT NULL GROUP BY pipeline_runs.company
   UNION ALL
   SELECT actions.account, max(actions.created_at) AS last_seen
     FROM actions WHERE actions.account IS NOT NULL GROUP BY actions.account
   UNION ALL
   SELECT campaigns.account, max(campaigns.created_at) AS last_seen
     FROM campaigns WHERE campaigns.account IS NOT NULL GROUP BY campaigns.account
   UNION ALL
   SELECT engagement_events.account, max(engagement_events.occurred_at) AS last_seen
     FROM engagement_events WHERE engagement_events.account IS NOT NULL GROUP BY engagement_events.account
 ) x GROUP BY account ORDER BY max(last_seen) DESC NULLS LAST;

create or replace view dashboard_account_actions as
 SELECT a.id, a.account, a.run_id, a.campaign_id, a.action_type, a.status, a.created_at,
   a.executed_at, a.decided_at, a.hypothesis, a.predicted_metric, a.predicted_direction,
   a.threshold, a.target, a.reason, a.tracked_url, a.utm_campaign, a.outreach_draft,
   a.channel_source, a.channel_reco_reason, a.rejection_reason, a.rejection_routed_to,
   o.result AS outcome_result, o.measured_value, o.baseline_value, o.effect, o.measured_at
 FROM actions a LEFT JOIN LATERAL (
   SELECT o2.id, o2.action_id, o2.measured_metric, o2.measured_value, o2.baseline_value,
     o2.effect, o2.result, o2.source, o2.window_start, o2.window_end, o2.measured_at, o2.notes
   FROM outcomes o2 WHERE o2.action_id = a.id ORDER BY o2.measured_at DESC LIMIT 1
 ) o ON true
 ORDER BY a.account, a.created_at DESC;

-- Unified "why did automation do this" feed for Account 360 — one row per
-- AI/adaptive decision regardless of whether it landed on an action,
-- cadence_step, or campaign. decision_type: 'channel_reco' (Channel
-- Recommendation AI picked a channel), 'adaptive' (Adaptive Decision Engine
-- escalated/paused/stopped/reviewed a step), 'campaign_completion' (a
-- campaign reached a terminal completion_reason, e.g. goal_met).
create or replace view dashboard_ai_decisions as
 SELECT 'channel_reco' AS decision_type, a.account, a.created_at AS decided_at, a.action_type,
   NULL::text AS decision_label, a.channel_reco_reason AS reason, a.id AS action_id, a.campaign_id
   FROM actions a WHERE a.channel_source = 'ai' AND a.channel_reco_reason IS NOT NULL
 UNION ALL
 SELECT 'channel_reco' AS decision_type, cs.account, cs.created_at AS decided_at, cs.action_type,
   NULL::text AS decision_label, cs.channel_reco_reason AS reason, cs.action_id, cs.campaign_id
   FROM cadence_steps cs WHERE cs.channel_source = 'ai' AND cs.channel_reco_reason IS NOT NULL AND cs.action_id IS NULL
 UNION ALL
 SELECT 'adaptive' AS decision_type, cs.account, COALESCE(o.measured_at, cs.created_at) AS decided_at,
   cs.action_type, cs.adaptive_action AS decision_label, cs.adaptive_reason AS reason, cs.action_id, cs.campaign_id
   FROM cadence_steps cs LEFT JOIN LATERAL (
     SELECT o2.measured_at FROM outcomes o2 WHERE o2.action_id = cs.action_id ORDER BY o2.measured_at DESC LIMIT 1
   ) o ON true
   WHERE cs.adaptive_action IS NOT NULL
 UNION ALL
 SELECT 'campaign_completion' AS decision_type, c.account, c.created_at AS decided_at,
   NULL::text AS action_type, c.status AS decision_label, c.completion_reason AS reason,
   NULL::bigint AS action_id, c.id AS campaign_id
   FROM campaigns c WHERE c.completion_reason IS NOT NULL
 ORDER BY 3 DESC;

create or replace view dashboard_engagement_funnel as  SELECT
  (SELECT count(*) FROM actions WHERE status = ANY (ARRAY['executed','measured'])) AS executed,
  (SELECT count(*) FROM engagement_events WHERE event_type = 'email_open') AS opened,
  (SELECT count(*) FROM engagement_events WHERE event_type = ANY (ARRAY['reply','email_reply'])) AS replied,
  (SELECT count(*) FROM engagement_events WHERE event_type = 'meeting_booked') AS meetings,
  (SELECT count(*) FROM engagement_events WHERE event_type = 'opportunity_created') AS opportunities;

-- Campaigns & cadences rollups
-- Note: this view has accreted columns across several phases (template_key in
-- the campaign-templates build, salesforce_* in the Salesforce sync prototype,
-- completion_reason in Phase 4, opportunity_* in the 2026-06-30 Opportunity
-- creation build) — kept in one GROUP BY rather than split, since every added
-- column is a plain campaigns column (1:1 with c.id), not a new aggregate.
create or replace view dashboard_campaigns as
 SELECT c.id AS campaign_id, c.run_id, c.account, c.status, c.template_key,
   to_char(c.created_at AT TIME ZONE 'Asia/Singapore', 'MM-DD HH24:MI') AS created_sgt,
   count(cs.id) AS total_steps,
   count(cs.id) FILTER (WHERE cs.status = ANY (ARRAY['executed','measured'])) AS completed_steps,
   count(cs.id) FILTER (WHERE cs.status = 'recommended') AS awaiting_approval_steps,
   count(cs.id) FILTER (WHERE cs.status = 'pending') AS upcoming_steps,
   count(cs.id) FILTER (WHERE cs.status = 'cancelled') AS cancelled_steps,
   count(cs.id) FILTER (WHERE cs.status = 'skipped') AS skipped_steps,
   min(cs.scheduled_for) FILTER (WHERE cs.status = 'pending') AS next_step_due,
   c.completion_reason,
   c.salesforce_campaign_id, c.salesforce_sync_status, c.salesforce_synced_at, c.salesforce_sync_error,
   c.salesforce_opportunity_id, c.opportunity_status, c.opportunity_offered_at, c.opportunity_created_at, c.opportunity_error,
   c.template_match_trace  -- 2026-06-30: template-selection audit trail (item 1), Account 360
 FROM campaigns c LEFT JOIN cadence_steps cs ON cs.campaign_id = c.id
 GROUP BY c.id, c.run_id, c.account, c.status, c.template_key, c.created_at, c.completion_reason,
   c.salesforce_campaign_id, c.salesforce_sync_status, c.salesforce_synced_at, c.salesforce_sync_error,
   c.salesforce_opportunity_id, c.opportunity_status, c.opportunity_offered_at, c.opportunity_created_at, c.opportunity_error,
   c.template_match_trace
 ORDER BY c.created_at DESC;

create or replace view dashboard_cadence_steps as
 SELECT cs.id, cs.campaign_id, c.account, cs.step_number, cs.delay_days, cs.scheduled_for,
   to_char(cs.scheduled_for AT TIME ZONE 'Asia/Singapore', 'MM-DD HH24:MI') AS scheduled_sgt,
   cs.action_type, cs.target, cs.reason, cs.status, cs.action_id,
   cs.channel_source, cs.channel_reco_reason,  -- 2026-06-29 Phase 5: channel recommendation AI
   cs.adaptive_action, cs.adaptive_reason      -- 2026-06-29 Phase 4: adaptive decision engine
 FROM cadence_steps cs JOIN campaigns c ON c.id = cs.campaign_id
 ORDER BY c.account, cs.step_number;

-- Grant read on dashboard/console views to the dashboard's anon role.
-- SELECT only — never insert/update/delete/truncate, even on views that
-- aren't auto-updatable. (feedback_for_tabita / feedback_for_engine ARE
-- auto-updatable single-table views over `actions`; a broader grant here
-- previously let anon write to `actions` straight through them. See
-- PROJECT_AUDIT.md, 2026-06-28 second pass.)
--
-- 2026-06-28, third occurrence: this project's `public` schema has a
-- default ACL (ALTER DEFAULT PRIVILEGES FOR ROLE postgres) that grants ALL
-- on every newly created relation to anon/authenticated. A plain
-- `grant select` on a brand-new view does NOT clear that — it only adds
-- SELECT on top of the INSERT/UPDATE/DELETE/TRUNCATE the default ACL
-- already granted at CREATE time. console_open_actions and
-- console_recent_engagement (both simple, single-table, auto-updatable
-- views) shipped with full anon CRUD straight through to `actions` /
-- `engagement_events` until caught in testing. Any NEW view added here
-- MUST get an explicit `revoke all ... from anon, authenticated, public`
-- before its `grant select` — don't trust the grant alone.
revoke all on console_open_actions, console_recent_engagement from anon, authenticated, public;
grant select on
  dashboard_kpis, dashboard_coverage, dashboard_trigger_type, dashboard_trend,
  dashboard_error_health, dashboard_action_funnel, dashboard_hypothesis_winrate,
  console_pending_briefs, console_pending_actions, dashboard_rejection_reasons,
  dashboard_correction_rate, attribution_last_touch, dashboard_attribution_summary,
  dashboard_channel_performance, dashboard_by_industry, dashboard_by_theme,
  dashboard_by_trigger, dashboard_enrichment, feedback_for_source, feedback_for_engine_logic,
  dashboard_gate1_breakdown, dashboard_vetoed_companies, dashboard_action_type,
  account_score, dashboard_top_accounts, dashboard_engagement_funnel,
  dashboard_campaigns, dashboard_cadence_steps, console_open_actions, console_recent_engagement,
  dashboard_channel_source_performance,
  dashboard_accounts_list, dashboard_account_actions, dashboard_ai_decisions  -- 2026-06-30: Account 360
to anon, authenticated;
