-- ============================================================
-- DP Syntropy — Supabase schema (pipeline + dashboard)
-- Project: fqsqoxsosavjhdsvfevk  (region ap-southeast-2)
-- Generated from live DB. Run against a fresh Postgres/Supabase
-- project to reproduce tables, views, and config access.
-- ============================================================

-- ---------- Core tables ----------

create table if not exists pipeline_runs (
  id integer primary key generated by default as identity,
  run_at timestamptz default now(),
  company text,
  trigger_type text,
  is_actionable boolean,
  coverage_label text,
  engaged_count integer,
  total_count integer,
  gate1_score integer,
  gate1_threshold integer,
  gate1_confidence text,
  gate1_rationale text,
  gate1_vetoed boolean,
  gate1_veto_reason text,
  gate1_result text,
  gate2_result text,
  brief_generated boolean,
  brief_s3_url text,
  human_approved boolean,
  notes text,
  when_urgency text,
  when_stage text,
  cap_archetype text,
  cap_confidence text,
  source text,
  raw_payload text,          -- original WHEN-layer brief JSON (for rejection echo)
  industry text,             -- segmentation
  theme text,                -- segmentation
  trigger_notes text,        -- segmentation (WHEN change_triggers.notes)
  enrichment_needed boolean  -- buying group has unconfirmed contacts
);

create table if not exists actions (
  id bigint primary key generated by default as identity,
  run_id integer references pipeline_runs(id),
  account text,
  action_type text,
  hypothesis text,
  predicted_metric text,
  predicted_direction text,
  threshold numeric,
  window_days integer,
  utm_campaign text,
  status text,               -- recommended | executed | measured | cancelled
  created_at timestamptz default now(),
  executed_at timestamptz,
  tracked_url text,
  rejection_reason text,
  rejection_routed_to text,  -- tabita | engine
  decided_at timestamptz,
  outreach_draft text        -- WHEN engine's ready-made outreach copy
);

create table if not exists outcomes (
  id bigint primary key generated by default as identity,
  action_id bigint references actions(id),
  measured_metric text,
  measured_value numeric,
  baseline_value numeric,
  effect numeric,
  result text,               -- met | not_met
  source text,               -- ga4 | gmail
  window_start timestamptz,
  window_end timestamptz,
  measured_at timestamptz default now(),
  notes text
);

create table if not exists pipeline_errors (
  id integer primary key generated by default as identity,
  occurred_at timestamptz default now(),
  company text,
  phase text,
  node_name text,
  error_msg text,
  resolved boolean default false
);

-- Raw engagement events (feeds attribution + channel-performance views)
create table if not exists engagement_events (
  id bigint primary key generated by default as identity,
  account text,
  contact text,
  source text,
  event_type text,           -- email_open | email_click | ad_click | page_visit | reply | meeting_booked | stage_change | form_fill
  campaign text,
  action_id bigint,
  value numeric,
  occurred_at timestamptz,
  metadata jsonb,
  ingested_at timestamptz default now()
);

-- Company-configurable settings (tracking domain, GA4 property, WHEN engine URL)
create table if not exists app_config (
  key text primary key,
  value text,
  description text,
  updated_at timestamptz not null default now()
);

insert into app_config (key, value, description) values
  ('tracking_base_url', '', 'Your GA4-tagged website that outreach tracking links point to'),
  ('ga4_property_id',  '', 'Your Google Analytics 4 numeric property ID'),
  ('when_engine_url',  '', 'WHEN Engine inbound URL; pipeline rejections are POSTed here')
on conflict (key) do nothing;

-- app_config: readable by anon (dashboard), updatable by anon (Settings tab)
alter table app_config enable row level security;
drop policy if exists app_config_read_public on app_config;
drop policy if exists app_config_anon_update on app_config;
create policy app_config_read_public on app_config for select to public using (true);
create policy app_config_anon_update on app_config for update to anon using (true) with check (true);
grant select on app_config to anon, authenticated;
grant update on app_config to anon;

-- ---------- Dashboard / console views ----------

create or replace view dashboard_kpis as  SELECT count(*) AS total,
    count(*) FILTER (WHERE gate1_result = 'PASS'::text) AS gate1_pass,
    count(*) FILTER (WHERE gate1_result = 'VETOED'::text) AS gate1_vetoed,
    count(*) FILTER (WHERE gate2_result = 'PASS'::text) AS gate2_pass,
    count(*) FILTER (WHERE brief_generated) AS briefs_generated,
    count(*) FILTER (WHERE human_approved) AS approved,
    count(*) FILTER (WHERE gate1_result = 'FAIL'::text AND gate2_result = 'PASS'::text) AS mismatch
   FROM pipeline_runs;

create or replace view dashboard_coverage as  SELECT COALESCE(coverage_label, 'Unknown'::text) AS label,
    count(*) AS n FROM pipeline_runs GROUP BY (COALESCE(coverage_label, 'Unknown'::text));

create or replace view dashboard_trigger_type as  SELECT
        CASE WHEN trigger_type IS NULL OR (TRIM(BOTH FROM trigger_type) = ANY (ARRAY[''::text, ':'::text])) THEN 'Unknown'::text
            ELSE split_part(trigger_type, ':'::text, 1) END AS label,
    count(*) AS n FROM pipeline_runs GROUP BY 1;

create or replace view dashboard_trend as  SELECT date_trunc('day'::text, (run_at AT TIME ZONE 'Asia/Singapore'::text)) AS day,
    count(*) AS n FROM pipeline_runs GROUP BY 1 ORDER BY 1;

create or replace view dashboard_error_health as  SELECT phase, node_name,
    count(*) AS errors, count(*) FILTER (WHERE NOT resolved) AS unresolved
   FROM pipeline_errors GROUP BY phase, node_name;

create or replace view dashboard_action_funnel as  SELECT count(*) AS total,
    count(*) FILTER (WHERE status <> 'cancelled'::text) AS recommended,
    count(*) FILTER (WHERE status = ANY (ARRAY['executed'::text, 'measured'::text])) AS executed,
    count(*) FILTER (WHERE status = 'measured'::text) AS measured,
    count(*) FILTER (WHERE status = 'cancelled'::text) AS cancelled
   FROM actions;

create or replace view dashboard_hypothesis_winrate as  SELECT a.action_type,
    count(o.id) AS measured,
    count(o.id) FILTER (WHERE o.result = 'met'::text) AS met,
    round(100.0 * count(o.id) FILTER (WHERE o.result = 'met'::text)::numeric / NULLIF(count(o.id), 0)::numeric, 0) AS win_rate_pct
   FROM actions a LEFT JOIN outcomes o ON o.action_id = a.id GROUP BY a.action_type;

create or replace view console_pending_briefs as  SELECT id, company, brief_s3_url, when_urgency, when_stage,
    to_char((run_at AT TIME ZONE 'Asia/Singapore'::text), 'MM-DD HH24:MI'::text) AS run_sgt
   FROM pipeline_runs
  WHERE human_approved = false AND brief_generated = true AND COALESCE(notes, ''::text) !~~* '%reject%'::text
  ORDER BY run_at DESC LIMIT 50;

create or replace view console_pending_actions as  SELECT a.id, a.account, a.action_type, a.hypothesis, a.predicted_metric,
    a.tracked_url, a.run_id, p.brief_s3_url, p.when_urgency, p.when_stage, a.created_at
   FROM actions a LEFT JOIN pipeline_runs p ON p.id = a.run_id
  WHERE a.status = 'recommended'::text ORDER BY a.created_at DESC;

create or replace view dashboard_rejection_reasons as  SELECT COALESCE(rejection_reason, '(unspecified)'::text) AS label,
    COALESCE(rejection_routed_to, '-'::text) AS routed_to, count(*) AS n
   FROM actions WHERE status = 'cancelled'::text GROUP BY rejection_reason, rejection_routed_to ORDER BY count(*) DESC;

create or replace view dashboard_correction_rate as  SELECT (decided_at AT TIME ZONE 'Asia/Singapore'::text)::date AS cycle,
    count(*) AS decided, count(*) FILTER (WHERE status = 'cancelled'::text) AS corrected,
    round(100.0 * count(*) FILTER (WHERE status = 'cancelled'::text)::numeric / NULLIF(count(*), 0)::numeric, 0) AS correction_rate_pct
   FROM actions WHERE decided_at IS NOT NULL GROUP BY 1 ORDER BY 1;

create or replace view attribution_last_touch as
 WITH conversions AS (SELECT * FROM engagement_events WHERE event_type = ANY (ARRAY['meeting_booked'::text, 'stage_change'::text, 'form_fill'::text])),
      touches AS (SELECT * FROM engagement_events WHERE event_type = ANY (ARRAY['email_click'::text, 'ad_click'::text, 'page_visit'::text, 'reply'::text]))
 SELECT c.id AS conversion_id, c.account, c.event_type AS conversion, c.occurred_at AS converted_at,
    t.campaign AS credited_campaign, t.source AS credited_source, t.occurred_at AS touch_at
   FROM conversions c
     LEFT JOIN LATERAL (SELECT * FROM touches t_1 WHERE t_1.account = c.account AND t_1.occurred_at <= c.occurred_at
          ORDER BY t_1.occurred_at DESC LIMIT 1) t ON true;

create or replace view dashboard_attribution_summary as  SELECT COALESCE(credited_campaign, '(direct/none)'::text) AS campaign,
    COALESCE(credited_source, '(direct/none)'::text) AS source, count(*) AS conversions
   FROM attribution_last_touch GROUP BY 1, 2 ORDER BY count(*) DESC;

create or replace view dashboard_channel_performance as
 WITH touches AS (SELECT source AS channel, count(*) AS touches FROM engagement_events
          WHERE event_type = ANY (ARRAY['email_open'::text, 'email_click'::text, 'ad_click'::text, 'page_visit'::text, 'reply'::text]) GROUP BY source),
      conv AS (SELECT credited_source AS channel, count(*) AS conversions FROM attribution_last_touch
          WHERE credited_source IS NOT NULL GROUP BY credited_source)
 SELECT COALESCE(t.channel, c.channel) AS channel, COALESCE(t.touches, 0::bigint) AS touches,
    COALESCE(c.conversions, 0::bigint) AS conversions,
    round(100.0 * COALESCE(c.conversions, 0::bigint)::numeric / NULLIF(COALESCE(t.touches, 0::bigint), 0)::numeric, 0) AS conv_rate_pct
   FROM touches t FULL JOIN conv c ON t.channel = c.channel ORDER BY 3 DESC, 2 DESC;

-- Segmentation + enrichment
create or replace view dashboard_by_industry as  SELECT COALESCE(NULLIF(industry, ''::text), 'Unknown'::text) AS label,
    count(*) AS n FROM pipeline_runs GROUP BY 1 ORDER BY count(*) DESC;

create or replace view dashboard_by_theme as  SELECT COALESCE(NULLIF(theme, ''::text), 'Unknown'::text) AS label,
    count(*) AS n FROM pipeline_runs GROUP BY 1 ORDER BY count(*) DESC;

create or replace view dashboard_by_trigger as  SELECT COALESCE(NULLIF(trigger_notes, ''::text), 'Unknown'::text) AS label,
    count(*) AS n FROM pipeline_runs GROUP BY 1 ORDER BY count(*) DESC;

create or replace view dashboard_enrichment as  SELECT count(*) FILTER (WHERE enrichment_needed) AS needs_enrichment,
    count(*) FILTER (WHERE enrichment_needed = false) AS enriched, count(*) AS total FROM pipeline_runs;

-- Feedback routing views (rejections)
create or replace view feedback_for_tabita as  SELECT id, account, action_type, rejection_reason, decided_at
   FROM actions WHERE status = 'cancelled'::text AND rejection_routed_to = 'tabita'::text ORDER BY decided_at DESC;

create or replace view feedback_for_engine as  SELECT id, account, action_type, rejection_reason, decided_at
   FROM actions WHERE status = 'cancelled'::text AND rejection_routed_to = 'engine'::text ORDER BY decided_at DESC;

-- Grant read on dashboard/console views to the dashboard's anon role
grant select on
  dashboard_kpis, dashboard_coverage, dashboard_trigger_type, dashboard_trend,
  dashboard_error_health, dashboard_action_funnel, dashboard_hypothesis_winrate,
  console_pending_briefs, console_pending_actions, dashboard_rejection_reasons,
  dashboard_correction_rate, attribution_last_touch, dashboard_attribution_summary,
  dashboard_channel_performance, dashboard_by_industry, dashboard_by_theme,
  dashboard_by_trigger, dashboard_enrichment, feedback_for_tabita, feedback_for_engine
to anon, authenticated;
