-- ============================================================
-- DP Syntropy — setup.sql — single-file bootstrap (DDL + seed data)
-- GENERATED from the live Supabase project fqsqoxsosavjhdsvfevk
-- on 2026-07-12 by direct catalog introspection. Do not hand-edit
-- past the point of divergence — regenerate instead.
-- Extensions live on the project: pg_cron 1.6.4, pg_net 0.20.3, pg_stat_statements 1.11, pgcrypto 1.3, plpgsql 1.0, supabase_vault 0.3.1, uuid-ossp 1.1, vector 0.8.0
--   (vector is INSTALLED but UNUSED by this pipeline — optional on re-home.)
-- 2026-07-13 fix pass: restored the 11 GENERATED..AS IDENTITY id columns the introspection
--   dropped, added the two missing serial sequences (pipeline_runs/pipeline_errors),
--   omitted the deprecated pipeline_runs_gate1_archive snapshot. Verified by executing the
--   full file against Postgres (schema-renamed, rolled back).
-- NOTE: the pg_cron job at the bottom requires the pg_cron extension
-- (Supabase: Database -> Extensions). Guarded so plain Postgres won't fail.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============ TABLES (FK dependency order) ============
CREATE TABLE public.action_channels (
  key text NOT NULL,
  label text NOT NULL,
  description text,
  is_high_touch boolean DEFAULT false NOT NULL,
  sort_order integer NOT NULL,
  CONSTRAINT action_channels_pkey PRIMARY KEY (key)
);
ALTER TABLE public.action_channels ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.action_channels FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.action_channels TO anon;
GRANT SELECT ON public.action_channels TO authenticated;
CREATE POLICY action_channels_read ON public.action_channels FOR SELECT TO anon,authenticated USING (true);

CREATE TABLE public.clients (
  id bigint GENERATED ALWAYS AS IDENTITY,
  name text NOT NULL,
  rep_email text,
  calendar_link text,
  status text DEFAULT 'active'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT clients_name_key UNIQUE (name),
  CONSTRAINT clients_pkey PRIMARY KEY (id)
);
REVOKE ALL ON public.clients FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.clients TO anon;
GRANT SELECT ON public.clients TO authenticated;

CREATE SEQUENCE public.pipeline_runs_id_seq;
CREATE TABLE public.pipeline_runs (
  id integer DEFAULT nextval('pipeline_runs_id_seq'::regclass) NOT NULL,
  run_at timestamp with time zone DEFAULT now(),
  company text,
  trigger_type text,
  is_actionable boolean,
  coverage_label text,
  engaged_count integer,
  total_count integer,
  brief_generated boolean DEFAULT false,
  brief_s3_url text,
  human_approved boolean,
  notes text,
  when_urgency text,
  when_stage text,
  cap_archetype text,
  cap_confidence text,
  source text,
  raw_payload text,
  industry text,
  theme text,
  trigger_notes text,
  enrichment_needed boolean,
  client_id bigint,
  CONSTRAINT pipeline_runs_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_runs_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id)
);
ALTER SEQUENCE public.pipeline_runs_id_seq OWNED BY public.pipeline_runs.id;
ALTER TABLE public.pipeline_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.pipeline_runs FROM anon, authenticated, PUBLIC;

CREATE TABLE public.campaigns (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  run_id integer,
  account text,
  status text DEFAULT 'active'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  salesforce_campaign_id text,
  salesforce_sync_status text DEFAULT 'pending'::text NOT NULL,
  salesforce_synced_at timestamp with time zone,
  salesforce_sync_error text,
  template_key text,
  completion_reason text,
  salesforce_opportunity_id text,
  opportunity_status text DEFAULT 'not_offered'::text NOT NULL,
  opportunity_offered_at timestamp with time zone,
  opportunity_created_at timestamp with time zone,
  opportunity_error text,
  template_match_trace jsonb,
  client_id bigint,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT campaigns_run_id_fkey FOREIGN KEY (run_id) REFERENCES pipeline_runs(id),
  CONSTRAINT campaigns_opportunity_status_check CHECK ((opportunity_status = ANY (ARRAY['not_offered'::text, 'offered'::text, 'created'::text, 'declined'::text, 'error'::text]))),
  CONSTRAINT campaigns_salesforce_sync_status_check CHECK ((salesforce_sync_status = ANY (ARRAY['pending'::text, 'synced'::text, 'error'::text, 'skipped'::text])))
);
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.campaigns FROM anon, authenticated, PUBLIC;

CREATE TABLE public.funnel_stages (
  key text NOT NULL,
  label text NOT NULL,
  sort_order integer NOT NULL,
  description text,
  CONSTRAINT funnel_stages_pkey PRIMARY KEY (key)
);
ALTER TABLE public.funnel_stages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.funnel_stages FROM anon, authenticated, PUBLIC;

CREATE TABLE public.campaign_objectives (
  id bigint GENERATED ALWAYS AS IDENTITY,
  campaign_id bigint NOT NULL,
  funnel_stage text NOT NULL,
  objective_key text NOT NULL,
  objective_label text,
  success_events text[] DEFAULT '{}'::text[] NOT NULL,
  target_value numeric DEFAULT 1 NOT NULL,
  window_days integer DEFAULT 21 NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  baseline_value numeric,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  met_at timestamp with time zone,
  CONSTRAINT campaign_objectives_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_objectives_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT campaign_objectives_funnel_stage_fkey FOREIGN KEY (funnel_stage) REFERENCES funnel_stages(key)
);
ALTER TABLE public.campaign_objectives ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.campaign_objectives FROM anon, authenticated, PUBLIC;

CREATE TABLE public.actions (
  id bigint GENERATED ALWAYS AS IDENTITY,
  run_id integer,
  account text,
  action_type text,
  hypothesis text,
  predicted_metric text,
  predicted_direction text DEFAULT 'increase'::text NOT NULL,
  threshold numeric,
  window_days integer DEFAULT 14 NOT NULL,
  utm_campaign text,
  status text DEFAULT 'recommended'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  executed_at timestamp with time zone,
  tracked_url text,
  rejection_reason text,
  rejection_routed_to text,
  decided_at timestamp with time zone,
  outreach_draft text,
  target text,
  priority integer,
  reason text,
  campaign_id bigint,
  salesforce_task_id text,
  channel_source text DEFAULT 'template'::text NOT NULL,
  channel_reco_reason text,
  objective_id bigint,
  funnel_stage text,
  tool_campaign_id text,
  client_id bigint,
  CONSTRAINT actions_pkey PRIMARY KEY (id),
  CONSTRAINT actions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id),
  CONSTRAINT actions_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT actions_funnel_stage_fkey FOREIGN KEY (funnel_stage) REFERENCES funnel_stages(key),
  CONSTRAINT actions_objective_id_fkey FOREIGN KEY (objective_id) REFERENCES campaign_objectives(id),
  CONSTRAINT actions_run_id_fkey FOREIGN KEY (run_id) REFERENCES pipeline_runs(id),
  CONSTRAINT actions_predicted_direction_check CHECK ((predicted_direction = ANY (ARRAY['increase'::text, 'decrease'::text]))),
  CONSTRAINT actions_status_check CHECK ((status = ANY (ARRAY['recommended'::text, 'executed'::text, 'measured'::text, 'cancelled'::text])))
);
ALTER TABLE public.actions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.actions FROM anon, authenticated, PUBLIC;

CREATE TABLE public.app_config (
  key text NOT NULL,
  value text,
  description text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT app_config_pkey PRIMARY KEY (key)
);
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.app_config FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.app_config TO anon;
CREATE POLICY app_config_anon_update ON public.app_config FOR UPDATE TO anon USING ((key = ANY (ARRAY['tracking_base_url'::text, 'ga4_property_id'::text, 'rep_notification_email'::text, 'approval_required_channels'::text, 'recommendation_expiry_days'::text, 'when_engine_url'::text]))) WITH CHECK ((key = ANY (ARRAY['tracking_base_url'::text, 'ga4_property_id'::text, 'rep_notification_email'::text, 'approval_required_channels'::text, 'recommendation_expiry_days'::text, 'when_engine_url'::text])));
CREATE POLICY app_config_read_public ON public.app_config FOR SELECT TO public USING ((key <> 'approval_hmac_secret'::text));

CREATE TABLE public.cadence_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  campaign_id bigint,
  account text,
  step_number integer,
  delay_days integer DEFAULT 0 NOT NULL,
  scheduled_for timestamp with time zone,
  action_type text,
  target text,
  reason text,
  hypothesis text,
  predicted_metric text,
  predicted_direction text,
  threshold numeric,
  window_days integer,
  utm_campaign text,
  tracked_url text,
  outreach_draft text,
  status text DEFAULT 'pending'::text NOT NULL,
  action_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  channel_source text DEFAULT 'template'::text NOT NULL,
  channel_reco_reason text,
  adaptive_action text,
  adaptive_reason text,
  objective_id bigint,
  funnel_stage text,
  CONSTRAINT cadence_steps_pkey PRIMARY KEY (id),
  CONSTRAINT cadence_steps_action_id_fkey FOREIGN KEY (action_id) REFERENCES actions(id),
  CONSTRAINT cadence_steps_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT cadence_steps_funnel_stage_fkey FOREIGN KEY (funnel_stage) REFERENCES funnel_stages(key),
  CONSTRAINT cadence_steps_objective_id_fkey FOREIGN KEY (objective_id) REFERENCES campaign_objectives(id)
);
ALTER TABLE public.cadence_steps ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.cadence_steps FROM anon, authenticated, PUBLIC;

CREATE TABLE public.campaign_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  key text NOT NULL,
  name text NOT NULL,
  description text,
  match_urgency_in text[],
  match_coverage_in text[],
  match_stage_contains text,
  priority integer NOT NULL,
  steps jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  match_keywords text[],
  goal text,
  kpi_metric text,
  kpi_target text,
  funnel_stage text,
  objective_success_events text[],
  objective_target_value numeric DEFAULT 1,
  objective_window_days integer DEFAULT 21,
  CONSTRAINT campaign_templates_key_key UNIQUE (key),
  CONSTRAINT campaign_templates_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_templates_funnel_stage_fkey FOREIGN KEY (funnel_stage) REFERENCES funnel_stages(key)
);
ALTER TABLE public.campaign_templates ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.campaign_templates FROM anon, authenticated, PUBLIC;

CREATE TABLE public.client_onboarding (
  id bigint GENERATED ALWAYS AS IDENTITY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  client_name text NOT NULL,
  rep_email text NOT NULL,
  calendar_link text,
  sender_account text,
  notes text,
  source text DEFAULT 'form'::text NOT NULL,
  raw jsonb,
  CONSTRAINT client_onboarding_pkey PRIMARY KEY (id)
);
REVOKE ALL ON public.client_onboarding FROM anon, authenticated, PUBLIC;

CREATE TABLE public.engagement_events (
  id bigint GENERATED ALWAYS AS IDENTITY,
  account text,
  contact text,
  source text,
  event_type text,
  campaign text,
  action_id bigint,
  value numeric,
  occurred_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  ingested_at timestamp with time zone DEFAULT now(),
  forwarded boolean DEFAULT false NOT NULL,
  salesforce_activity_id text,
  client_id bigint,
  CONSTRAINT engagement_events_pkey PRIMARY KEY (id),
  CONSTRAINT engagement_events_action_id_fkey FOREIGN KEY (action_id) REFERENCES actions(id),
  CONSTRAINT engagement_events_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id)
);
ALTER TABLE public.engagement_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.engagement_events FROM anon, authenticated, PUBLIC;

CREATE TABLE public.heartbeat_expected (
  workflow_id text NOT NULL,
  name text NOT NULL,
  kind text NOT NULL,
  max_silence_hours integer,
  enabled boolean DEFAULT true NOT NULL,
  note text,
  CONSTRAINT heartbeat_expected_pkey PRIMARY KEY (workflow_id),
  CONSTRAINT heartbeat_expected_kind_check CHECK ((kind = ANY (ARRAY['schedule'::text, 'webhook'::text])))
);
ALTER TABLE public.heartbeat_expected ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.heartbeat_expected FROM anon, authenticated, PUBLIC;

CREATE TABLE public.linkedin_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  account text,
  topic text,
  post_body text NOT NULL,
  tracked_url text,
  status text DEFAULT 'pending_approval'::text NOT NULL,
  rejection_reason text,
  posted_url text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  decided_at timestamp with time zone,
  posted_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT linkedin_posts_pkey PRIMARY KEY (id)
);
REVOKE ALL ON public.linkedin_posts FROM anon, authenticated, PUBLIC;

CREATE TABLE public.outcomes (
  id bigint GENERATED ALWAYS AS IDENTITY,
  action_id bigint NOT NULL,
  measured_metric text,
  measured_value numeric,
  baseline_value numeric,
  effect numeric,
  result text,
  source text,
  window_start timestamp with time zone,
  window_end timestamp with time zone,
  measured_at timestamp with time zone DEFAULT now() NOT NULL,
  notes text,
  CONSTRAINT outcomes_pkey PRIMARY KEY (id),
  CONSTRAINT outcomes_action_id_fkey FOREIGN KEY (action_id) REFERENCES actions(id) ON DELETE CASCADE,
  CONSTRAINT outcomes_result_check CHECK ((result = ANY (ARRAY['met'::text, 'not_met'::text, 'inconclusive'::text])))
);
ALTER TABLE public.outcomes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.outcomes FROM anon, authenticated, PUBLIC;

CREATE SEQUENCE public.pipeline_errors_id_seq;
CREATE TABLE public.pipeline_errors (
  id integer DEFAULT nextval('pipeline_errors_id_seq'::regclass) NOT NULL,
  occurred_at timestamp with time zone DEFAULT now(),
  company text,
  phase text,
  node_name text,
  error_msg text,
  resolved boolean DEFAULT false,
  CONSTRAINT pipeline_errors_pkey PRIMARY KEY (id)
);
ALTER SEQUENCE public.pipeline_errors_id_seq OWNED BY public.pipeline_errors.id;
ALTER TABLE public.pipeline_errors ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.pipeline_errors FROM anon, authenticated, PUBLIC;

-- (pipeline_runs_gate1_archive intentionally omitted: deprecated Gate1/Gate2-era snapshot,
--  kept live only as a safety copy of the 2026-07-07 trim; a fresh install has no use for it.)

CREATE TABLE public.salesforce_leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  account text NOT NULL,
  contact_name text NOT NULL,
  salesforce_lead_id text NOT NULL,
  campaign_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT salesforce_leads_salesforce_lead_id_key UNIQUE (salesforce_lead_id),
  CONSTRAINT salesforce_leads_pkey PRIMARY KEY (id),
  CONSTRAINT salesforce_leads_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id)
);
ALTER TABLE public.salesforce_leads ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.salesforce_leads FROM anon, authenticated, PUBLIC;

-- ============ INDEXES ============
CREATE INDEX idx_actions_campaign_id ON public.actions USING btree (campaign_id);
CREATE INDEX idx_actions_funnel_stage ON public.actions USING btree (funnel_stage);
CREATE INDEX idx_actions_run ON public.actions USING btree (run_id);
CREATE INDEX idx_actions_status ON public.actions USING btree (status);
CREATE INDEX idx_actions_utm ON public.actions USING btree (utm_campaign);
CREATE INDEX ix_actions_objective ON public.actions USING btree (objective_id);
CREATE INDEX idx_cadence_steps_action ON public.cadence_steps USING btree (action_id);
CREATE INDEX idx_cadence_steps_campaign ON public.cadence_steps USING btree (campaign_id);
CREATE INDEX idx_cadence_steps_due ON public.cadence_steps USING btree (status, scheduled_for) WHERE (status = 'pending'::text);
CREATE INDEX idx_cadence_steps_funnel_stage ON public.cadence_steps USING btree (funnel_stage);
CREATE INDEX ix_cadence_steps_objective ON public.cadence_steps USING btree (objective_id);
CREATE INDEX idx_campaign_objectives_funnel_stage ON public.campaign_objectives USING btree (funnel_stage);
CREATE INDEX ix_campaign_objectives_campaign ON public.campaign_objectives USING btree (campaign_id);
CREATE INDEX idx_campaign_templates_funnel_stage ON public.campaign_templates USING btree (funnel_stage);
CREATE INDEX idx_campaigns_run_id ON public.campaigns USING btree (run_id);
CREATE INDEX idx_engagement_events_action_id ON public.engagement_events USING btree (action_id);
CREATE INDEX idx_ev_account ON public.engagement_events USING btree (account);
CREATE INDEX idx_ev_campaign ON public.engagement_events USING btree (campaign);
CREATE INDEX idx_ev_time ON public.engagement_events USING btree (occurred_at);
CREATE UNIQUE INDEX uq_engagement_email_event ON public.engagement_events USING btree (source, ((metadata ->> 'email_event_id'::text))) WHERE ((source = 'email'::text) AND (COALESCE((metadata ->> 'email_event_id'::text), ''::text) <> ''::text));
CREATE UNIQUE INDEX uq_engagement_linkedin_event ON public.engagement_events USING btree (source, ((metadata ->> 'linkedin_event_id'::text))) WHERE ((source = 'linkedin'::text) AND (COALESCE((metadata ->> 'linkedin_event_id'::text), ''::text) <> ''::text));
CREATE INDEX idx_outcomes_action ON public.outcomes USING btree (action_id);
CREATE INDEX idx_salesforce_leads_campaign_id ON public.salesforce_leads USING btree (campaign_id);

-- ============ VIEWS (dependency order) ============
CREATE VIEW public.account_score AS
 WITH event_weights AS (
         SELECT ee.account,
            ee.source,
            ee.event_type,
            ee.occurred_at,
                CASE ee.event_type
                    WHEN 'opportunity_created'::text THEN 50
                    WHEN 'meeting_booked'::text THEN 40
                    WHEN 'reply_or_meeting'::text THEN 30
                    WHEN 'reply'::text THEN 20
                    WHEN 'email_reply'::text THEN 20
                    WHEN 'form_fill'::text THEN 25
                    WHEN 'call_connected'::text THEN 25
                    WHEN 'registration'::text THEN 15
                    WHEN 'content_download'::text THEN 15
                    WHEN 'stage_change'::text THEN 15
                    WHEN 'partner_response'::text THEN 15
                    WHEN 'linkedin_accept'::text THEN 10
                    WHEN 'email_click'::text THEN 5
                    WHEN 'email_open'::text THEN 5
                    WHEN 'page_visit'::text THEN 5
                    WHEN 'profile_visit'::text THEN 5
                    ELSE 2
                END AS base_weight,
            row_number() OVER (PARTITION BY ee.account, ee.event_type ORDER BY ee.occurred_at) AS occurrence_rank
           FROM engagement_events ee
          WHERE ee.account IS NOT NULL
        ), ev AS (
         SELECT event_weights.account,
            sum(event_weights.base_weight::numeric *
                CASE event_weights.occurrence_rank
                    WHEN 1 THEN 1.0
                    WHEN 2 THEN 0.4
                    ELSE 0::numeric
                END) AS event_points,
            sum(event_weights.base_weight::numeric *
                CASE event_weights.occurrence_rank
                    WHEN 1 THEN 1.0
                    WHEN 2 THEN 0.4
                    ELSE 0::numeric
                END) FILTER (WHERE event_weights.source = ANY (ARRAY['ga4'::text, 'gmail'::text, 'salesforce'::text])) AS hard_event_points,
            sum(event_weights.base_weight::numeric *
                CASE event_weights.occurrence_rank
                    WHEN 1 THEN 1.0
                    WHEN 2 THEN 0.4
                    ELSE 0::numeric
                END) FILTER (WHERE event_weights.source = 'manual'::text) AS soft_points,
            count(*) AS events,
            max(event_weights.occurred_at) AS last_event
           FROM event_weights
          GROUP BY event_weights.account
        ), base AS (
         SELECT pipeline_runs.company AS account,
            max(
                CASE upper(COALESCE(pipeline_runs.coverage_label, ''::text))
                    WHEN 'BROAD'::text THEN 15
                    WHEN 'PARTIAL'::text THEN 10
                    WHEN 'NARROW'::text THEN 5
                    ELSE 0
                END) + max(
                CASE
                    WHEN upper(COALESCE(pipeline_runs.when_urgency, ''::text)) = ANY (ARRAY['URGENT'::text, 'LIVE'::text, 'HIGH'::text, 'ACT NOW'::text]) THEN 10
                    ELSE 0
                END) AS base_points
           FROM pipeline_runs
          WHERE pipeline_runs.company IS NOT NULL
          GROUP BY pipeline_runs.company
        )
 SELECT COALESCE(ev.account, base.account) AS account,
    LEAST(round((COALESCE(base.base_points, 0)::numeric + COALESCE(ev.event_points, 0::numeric))::double precision)::integer, 100) AS score,
    COALESCE(ev.events, 0::bigint) AS engagement_events,
    ev.last_event,
    round((COALESCE(base.base_points, 0)::numeric + COALESCE(ev.hard_event_points, 0::numeric))::double precision)::integer AS hard_points,
    round(COALESCE(ev.soft_points, 0::numeric)::double precision)::integer AS soft_points
   FROM ev
     FULL JOIN base ON ev.account = base.account;
REVOKE ALL ON public.account_score FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.account_score TO anon;
GRANT SELECT ON public.account_score TO authenticated;

CREATE VIEW public.attribution_last_touch AS
 WITH conversions AS (
         SELECT engagement_events.id,
            engagement_events.account,
            engagement_events.contact,
            engagement_events.source,
            engagement_events.event_type,
            engagement_events.campaign,
            engagement_events.action_id,
            engagement_events.value,
            engagement_events.occurred_at,
            engagement_events.metadata,
            engagement_events.ingested_at
           FROM engagement_events
          WHERE engagement_events.event_type = ANY (ARRAY['meeting_booked'::text, 'stage_change'::text, 'form_fill'::text])
        ), touches AS (
         SELECT engagement_events.id,
            engagement_events.account,
            engagement_events.contact,
            engagement_events.source,
            engagement_events.event_type,
            engagement_events.campaign,
            engagement_events.action_id,
            engagement_events.value,
            engagement_events.occurred_at,
            engagement_events.metadata,
            engagement_events.ingested_at
           FROM engagement_events
          WHERE engagement_events.event_type = ANY (ARRAY['email_click'::text, 'ad_click'::text, 'page_visit'::text, 'reply'::text])
        )
 SELECT c.id AS conversion_id,
    c.account,
    c.event_type AS conversion,
    c.occurred_at AS converted_at,
    t.campaign AS credited_campaign,
    t.source AS credited_source,
    t.occurred_at AS touch_at
   FROM conversions c
     LEFT JOIN LATERAL ( SELECT t_1.id,
            t_1.account,
            t_1.contact,
            t_1.source,
            t_1.event_type,
            t_1.campaign,
            t_1.action_id,
            t_1.value,
            t_1.occurred_at,
            t_1.metadata,
            t_1.ingested_at
           FROM touches t_1
          WHERE t_1.account = c.account AND t_1.occurred_at <= c.occurred_at
          ORDER BY t_1.occurred_at DESC
         LIMIT 1) t ON true;
REVOKE ALL ON public.attribution_last_touch FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.attribution_last_touch TO anon;
GRANT SELECT ON public.attribution_last_touch TO authenticated;

CREATE VIEW public.console_my_day AS
 SELECT id,
    account,
    action_type,
    target,
    reason,
    outreach_draft,
    tracked_url,
    status,
    priority,
    utm_campaign,
    predicted_metric,
    created_at,
    executed_at,
        CASE
            WHEN status = 'executed'::text THEN 'ready'::text
            ELSE 'pending'::text
        END AS bucket
   FROM actions a
  WHERE status = 'executed'::text AND executed_at >= (date_trunc('day'::text, (now() AT TIME ZONE 'Asia/Singapore'::text)) AT TIME ZONE 'Asia/Singapore'::text) OR status = 'recommended'::text
  ORDER BY account, status DESC, priority, created_at;
REVOKE ALL ON public.console_my_day FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.console_my_day TO anon;
GRANT SELECT ON public.console_my_day TO authenticated;

CREATE VIEW public.console_open_actions AS
 SELECT id,
    account,
    action_type,
    target,
    predicted_metric,
    utm_campaign,
    tracked_url,
    executed_at,
    hypothesis,
    reason
   FROM actions a
  WHERE status = 'executed'::text
  ORDER BY executed_at DESC;
REVOKE ALL ON public.console_open_actions FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.console_open_actions TO anon;
GRANT SELECT ON public.console_open_actions TO authenticated;

CREATE VIEW public.console_pending_actions AS
 SELECT a.id,
    a.account,
    a.action_type,
    a.target,
    a.priority,
    a.reason,
    a.hypothesis,
    a.predicted_metric,
    a.tracked_url,
    a.run_id,
    p.brief_s3_url,
    p.when_urgency,
    p.when_stage,
    a.created_at,
    to_char((a.created_at AT TIME ZONE 'Asia/Singapore'::text), 'MM-DD HH24:MI'::text) AS created_sgt
   FROM actions a
     LEFT JOIN pipeline_runs p ON p.id = a.run_id
  WHERE a.status = 'recommended'::text
  ORDER BY a.created_at DESC, a.priority;
REVOKE ALL ON public.console_pending_actions FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.console_pending_actions TO anon;
GRANT SELECT ON public.console_pending_actions TO authenticated;

CREATE VIEW public.console_pending_briefs AS
 SELECT id,
    company,
    brief_s3_url,
    when_urgency,
    when_stage,
    to_char((run_at AT TIME ZONE 'Asia/Singapore'::text), 'MM-DD HH24:MI'::text) AS run_sgt
   FROM pipeline_runs
  WHERE human_approved = false AND brief_generated = true AND COALESCE(notes, ''::text) !~~* '%reject%'::text
  ORDER BY run_at DESC
 LIMIT 50;
REVOKE ALL ON public.console_pending_briefs FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.console_pending_briefs TO anon;
GRANT SELECT ON public.console_pending_briefs TO authenticated;

CREATE VIEW public.console_recent_engagement AS
 SELECT id,
    account,
    event_type,
    source,
    campaign,
    action_id,
    value,
    occurred_at,
    metadata,
    ingested_at
   FROM engagement_events
  ORDER BY ingested_at DESC;
REVOKE ALL ON public.console_recent_engagement FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.console_recent_engagement TO anon;
GRANT SELECT ON public.console_recent_engagement TO authenticated;

CREATE VIEW public.dashboard_account_actions AS
 SELECT a.id,
    a.account,
    a.run_id,
    a.campaign_id,
    a.action_type,
    a.status,
    a.created_at,
    a.executed_at,
    a.decided_at,
    a.hypothesis,
    a.predicted_metric,
    a.predicted_direction,
    a.threshold,
    a.target,
    a.reason,
    a.tracked_url,
    a.utm_campaign,
    a.outreach_draft,
    a.channel_source,
    a.channel_reco_reason,
    a.rejection_reason,
    a.rejection_routed_to,
    o.result AS outcome_result,
    o.measured_value,
    o.baseline_value,
    o.effect,
    o.measured_at
   FROM actions a
     LEFT JOIN LATERAL ( SELECT o2.id,
            o2.action_id,
            o2.measured_metric,
            o2.measured_value,
            o2.baseline_value,
            o2.effect,
            o2.result,
            o2.source,
            o2.window_start,
            o2.window_end,
            o2.measured_at,
            o2.notes
           FROM outcomes o2
          WHERE o2.action_id = a.id
          ORDER BY o2.measured_at DESC
         LIMIT 1) o ON true
  ORDER BY a.account, a.created_at DESC;
REVOKE ALL ON public.dashboard_account_actions FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_account_actions TO anon;
GRANT SELECT ON public.dashboard_account_actions TO authenticated;

CREATE VIEW public.dashboard_accounts_list AS
 SELECT account,
    max(last_seen) AS last_seen
   FROM ( SELECT pipeline_runs.company AS account,
            max(pipeline_runs.run_at) AS last_seen
           FROM pipeline_runs
          WHERE pipeline_runs.company IS NOT NULL
          GROUP BY pipeline_runs.company
        UNION ALL
         SELECT actions.account,
            max(actions.created_at) AS last_seen
           FROM actions
          WHERE actions.account IS NOT NULL
          GROUP BY actions.account
        UNION ALL
         SELECT campaigns.account,
            max(campaigns.created_at) AS last_seen
           FROM campaigns
          WHERE campaigns.account IS NOT NULL
          GROUP BY campaigns.account
        UNION ALL
         SELECT engagement_events.account,
            max(engagement_events.occurred_at) AS last_seen
           FROM engagement_events
          WHERE engagement_events.account IS NOT NULL
          GROUP BY engagement_events.account) x
  GROUP BY account
  ORDER BY (max(last_seen)) DESC NULLS LAST;
REVOKE ALL ON public.dashboard_accounts_list FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_accounts_list TO anon;
GRANT SELECT ON public.dashboard_accounts_list TO authenticated;

CREATE VIEW public.dashboard_action_funnel AS
 SELECT count(*) AS total,
    count(*) FILTER (WHERE status <> 'cancelled'::text) AS recommended,
    count(*) FILTER (WHERE status = ANY (ARRAY['executed'::text, 'measured'::text])) AS executed,
    count(*) FILTER (WHERE status = 'measured'::text) AS measured,
    count(*) FILTER (WHERE status = 'cancelled'::text) AS cancelled
   FROM actions;
REVOKE ALL ON public.dashboard_action_funnel FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_action_funnel TO anon;
GRANT SELECT ON public.dashboard_action_funnel TO authenticated;

CREATE VIEW public.dashboard_action_type AS
 SELECT action_type AS label,
    count(*) AS n
   FROM actions
  GROUP BY action_type;
REVOKE ALL ON public.dashboard_action_type FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_action_type TO anon;
GRANT SELECT ON public.dashboard_action_type TO authenticated;

CREATE VIEW public.dashboard_ai_decisions AS
 SELECT 'channel_reco'::text AS decision_type,
    a.account,
    a.created_at AS decided_at,
    a.action_type,
    NULL::text AS decision_label,
    a.channel_reco_reason AS reason,
    a.id AS action_id,
    a.campaign_id
   FROM actions a
  WHERE a.channel_source = 'ai'::text AND a.channel_reco_reason IS NOT NULL
UNION ALL
 SELECT 'channel_reco'::text AS decision_type,
    cs.account,
    cs.created_at AS decided_at,
    cs.action_type,
    NULL::text AS decision_label,
    cs.channel_reco_reason AS reason,
    cs.action_id,
    cs.campaign_id
   FROM cadence_steps cs
  WHERE cs.channel_source = 'ai'::text AND cs.channel_reco_reason IS NOT NULL AND cs.action_id IS NULL
UNION ALL
 SELECT 'adaptive'::text AS decision_type,
    cs.account,
    COALESCE(o.measured_at, cs.created_at) AS decided_at,
    cs.action_type,
    cs.adaptive_action AS decision_label,
    cs.adaptive_reason AS reason,
    cs.action_id,
    cs.campaign_id
   FROM cadence_steps cs
     LEFT JOIN LATERAL ( SELECT o2.measured_at
           FROM outcomes o2
          WHERE o2.action_id = cs.action_id
          ORDER BY o2.measured_at DESC
         LIMIT 1) o ON true
  WHERE cs.adaptive_action IS NOT NULL
UNION ALL
 SELECT 'campaign_completion'::text AS decision_type,
    c.account,
    c.created_at AS decided_at,
    NULL::text AS action_type,
    c.status AS decision_label,
    c.completion_reason AS reason,
    NULL::bigint AS action_id,
    c.id AS campaign_id
   FROM campaigns c
  WHERE c.completion_reason IS NOT NULL
  ORDER BY 3 DESC;
REVOKE ALL ON public.dashboard_ai_decisions FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_ai_decisions TO anon;
GRANT SELECT ON public.dashboard_ai_decisions TO authenticated;

CREATE VIEW public.dashboard_attribution_summary AS
 SELECT COALESCE(credited_campaign, '(direct/none)'::text) AS campaign,
    COALESCE(credited_source, '(direct/none)'::text) AS source,
    count(*) AS conversions
   FROM attribution_last_touch
  GROUP BY (COALESCE(credited_campaign, '(direct/none)'::text)), (COALESCE(credited_source, '(direct/none)'::text))
  ORDER BY (count(*)) DESC;
REVOKE ALL ON public.dashboard_attribution_summary FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_attribution_summary TO anon;
GRANT SELECT ON public.dashboard_attribution_summary TO authenticated;

CREATE VIEW public.dashboard_by_industry AS
 SELECT COALESCE(NULLIF(industry, ''::text), 'Unknown'::text) AS label,
    count(*) AS n
   FROM pipeline_runs
  GROUP BY (COALESCE(NULLIF(industry, ''::text), 'Unknown'::text))
  ORDER BY (count(*)) DESC;
REVOKE ALL ON public.dashboard_by_industry FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_by_industry TO anon;
GRANT SELECT ON public.dashboard_by_industry TO authenticated;

CREATE VIEW public.dashboard_by_theme AS
 SELECT COALESCE(NULLIF(theme, ''::text), 'Unknown'::text) AS label,
    count(*) AS n
   FROM pipeline_runs
  GROUP BY (COALESCE(NULLIF(theme, ''::text), 'Unknown'::text))
  ORDER BY (count(*)) DESC;
REVOKE ALL ON public.dashboard_by_theme FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_by_theme TO anon;
GRANT SELECT ON public.dashboard_by_theme TO authenticated;

CREATE VIEW public.dashboard_by_trigger AS
 SELECT COALESCE(NULLIF(trigger_notes, ''::text), 'Unknown'::text) AS label,
    count(*) AS n
   FROM pipeline_runs
  GROUP BY (COALESCE(NULLIF(trigger_notes, ''::text), 'Unknown'::text))
  ORDER BY (count(*)) DESC;
REVOKE ALL ON public.dashboard_by_trigger FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_by_trigger TO anon;
GRANT SELECT ON public.dashboard_by_trigger TO authenticated;

CREATE VIEW public.dashboard_cadence_steps AS
 SELECT cs.id,
    cs.campaign_id,
    c.account,
    cs.step_number,
    cs.delay_days,
    cs.scheduled_for,
    to_char((cs.scheduled_for AT TIME ZONE 'Asia/Singapore'::text), 'MM-DD HH24:MI'::text) AS scheduled_sgt,
    cs.action_type,
    cs.target,
    cs.reason,
    cs.status,
    cs.action_id,
    cs.channel_source,
    cs.channel_reco_reason,
    cs.adaptive_action,
    cs.adaptive_reason,
    cs.outreach_draft
   FROM cadence_steps cs
     JOIN campaigns c ON c.id = cs.campaign_id
  ORDER BY c.account, cs.step_number;
REVOKE ALL ON public.dashboard_cadence_steps FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_cadence_steps TO anon;
GRANT SELECT ON public.dashboard_cadence_steps TO authenticated;

CREATE VIEW public.dashboard_campaigns AS
 SELECT c.id AS campaign_id,
    c.run_id,
    c.account,
    c.status,
    c.template_key,
    to_char((c.created_at AT TIME ZONE 'Asia/Singapore'::text), 'MM-DD HH24:MI'::text) AS created_sgt,
    count(cs.id) AS total_steps,
    count(cs.id) FILTER (WHERE cs.status = ANY (ARRAY['executed'::text, 'measured'::text])) AS completed_steps,
    count(cs.id) FILTER (WHERE cs.status = 'recommended'::text) AS awaiting_approval_steps,
    count(cs.id) FILTER (WHERE cs.status = 'pending'::text) AS upcoming_steps,
    count(cs.id) FILTER (WHERE cs.status = 'cancelled'::text) AS cancelled_steps,
    count(cs.id) FILTER (WHERE cs.status = 'skipped'::text) AS skipped_steps,
    min(cs.scheduled_for) FILTER (WHERE cs.status = 'pending'::text) AS next_step_due,
    c.completion_reason,
    c.salesforce_campaign_id,
    c.salesforce_sync_status,
    c.salesforce_synced_at,
    c.salesforce_sync_error,
    c.salesforce_opportunity_id,
    c.opportunity_status,
    c.opportunity_offered_at,
    c.opportunity_created_at,
    c.opportunity_error,
    c.template_match_trace
   FROM campaigns c
     LEFT JOIN cadence_steps cs ON cs.campaign_id = c.id
  GROUP BY c.id, c.run_id, c.account, c.status, c.template_key, c.created_at, c.completion_reason, c.salesforce_campaign_id, c.salesforce_sync_status, c.salesforce_synced_at, c.salesforce_sync_error, c.salesforce_opportunity_id, c.opportunity_status, c.opportunity_offered_at, c.opportunity_created_at, c.opportunity_error, c.template_match_trace
  ORDER BY c.created_at DESC;
REVOKE ALL ON public.dashboard_campaigns FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_campaigns TO anon;
GRANT SELECT ON public.dashboard_campaigns TO authenticated;

CREATE VIEW public.dashboard_channel_performance AS
 WITH touches AS (
         SELECT engagement_events.source AS channel,
            count(*) AS touches
           FROM engagement_events
          WHERE engagement_events.event_type = ANY (ARRAY['email_open'::text, 'email_click'::text, 'ad_click'::text, 'page_visit'::text, 'reply'::text])
          GROUP BY engagement_events.source
        ), conv AS (
         SELECT attribution_last_touch.credited_source AS channel,
            count(*) AS conversions
           FROM attribution_last_touch
          WHERE attribution_last_touch.credited_source IS NOT NULL
          GROUP BY attribution_last_touch.credited_source
        )
 SELECT COALESCE(t.channel, c.channel) AS channel,
    COALESCE(t.touches, 0::bigint) AS touches,
    COALESCE(c.conversions, 0::bigint) AS conversions,
    round(100.0 * COALESCE(c.conversions, 0::bigint)::numeric / NULLIF(COALESCE(t.touches, 0::bigint), 0)::numeric, 0) AS conv_rate_pct
   FROM touches t
     FULL JOIN conv c ON t.channel = c.channel
  ORDER BY (COALESCE(c.conversions, 0::bigint)) DESC, (COALESCE(t.touches, 0::bigint)) DESC;
REVOKE ALL ON public.dashboard_channel_performance FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_channel_performance TO anon;
GRANT SELECT ON public.dashboard_channel_performance TO authenticated;

CREATE VIEW public.dashboard_channel_source_performance AS
 SELECT a.channel_source,
    count(*) AS total_actions,
    count(*) FILTER (WHERE a.status = ANY (ARRAY['executed'::text, 'measured'::text])) AS executed,
    count(o.id) AS measured,
    count(o.id) FILTER (WHERE o.result = 'met'::text) AS met,
    round(100.0 * count(o.id) FILTER (WHERE o.result = 'met'::text)::numeric / NULLIF(count(o.id), 0)::numeric, 0) AS win_rate_pct
   FROM actions a
     LEFT JOIN outcomes o ON o.action_id = a.id
  GROUP BY a.channel_source;
REVOKE ALL ON public.dashboard_channel_source_performance FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_channel_source_performance TO anon;
GRANT SELECT ON public.dashboard_channel_source_performance TO authenticated;

CREATE VIEW public.dashboard_client_overview AS
 SELECT c.id AS client_id,
    c.name AS client_name,
    c.rep_email,
    c.status,
    count(DISTINCT p.id) AS briefs,
    count(DISTINCT p.id) FILTER (WHERE p.human_approved) AS briefs_approved,
    count(DISTINCT cam.id) AS campaigns,
    count(DISTINCT cam.id) FILTER (WHERE cam.status = 'active'::text) AS campaigns_active,
    count(DISTINCT a.id) AS actions,
    count(DISTINCT e.id) AS engagement_events
   FROM clients c
     LEFT JOIN pipeline_runs p ON p.client_id = c.id
     LEFT JOIN campaigns cam ON cam.client_id = c.id
     LEFT JOIN actions a ON a.client_id = c.id
     LEFT JOIN engagement_events e ON e.client_id = c.id
  GROUP BY c.id, c.name, c.rep_email, c.status
  ORDER BY c.id;
REVOKE ALL ON public.dashboard_client_overview FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_client_overview TO anon;
GRANT SELECT ON public.dashboard_client_overview TO authenticated;

CREATE VIEW public.dashboard_correction_rate AS
 SELECT (decided_at AT TIME ZONE 'Asia/Singapore'::text)::date AS cycle,
    count(*) AS decided,
    count(*) FILTER (WHERE status = 'cancelled'::text) AS corrected,
    round(100.0 * count(*) FILTER (WHERE status = 'cancelled'::text)::numeric / NULLIF(count(*), 0)::numeric, 0) AS correction_rate_pct
   FROM actions
  WHERE decided_at IS NOT NULL
  GROUP BY ((decided_at AT TIME ZONE 'Asia/Singapore'::text)::date)
  ORDER BY ((decided_at AT TIME ZONE 'Asia/Singapore'::text)::date);
REVOKE ALL ON public.dashboard_correction_rate FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_correction_rate TO anon;
GRANT SELECT ON public.dashboard_correction_rate TO authenticated;

CREATE VIEW public.dashboard_coverage AS
 SELECT COALESCE(coverage_label, 'Unknown'::text) AS label,
    count(*) AS n
   FROM pipeline_runs
  GROUP BY (COALESCE(coverage_label, 'Unknown'::text));
REVOKE ALL ON public.dashboard_coverage FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_coverage TO anon;
GRANT SELECT ON public.dashboard_coverage TO authenticated;

CREATE VIEW public.dashboard_engagement_funnel AS
 SELECT ( SELECT count(*) AS count
           FROM actions
          WHERE actions.status = ANY (ARRAY['executed'::text, 'measured'::text])) AS executed,
    ( SELECT count(*) AS count
           FROM engagement_events
          WHERE engagement_events.event_type = 'email_open'::text) AS opened,
    ( SELECT count(*) AS count
           FROM engagement_events
          WHERE engagement_events.event_type = ANY (ARRAY['reply'::text, 'email_reply'::text])) AS replied,
    ( SELECT count(*) AS count
           FROM engagement_events
          WHERE engagement_events.event_type = 'meeting_booked'::text) AS meetings,
    ( SELECT count(*) AS count
           FROM engagement_events
          WHERE engagement_events.event_type = 'opportunity_created'::text) AS opportunities;
REVOKE ALL ON public.dashboard_engagement_funnel FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_engagement_funnel TO anon;
GRANT SELECT ON public.dashboard_engagement_funnel TO authenticated;

CREATE VIEW public.dashboard_enrichment AS
 SELECT count(*) FILTER (WHERE enrichment_needed) AS needs_enrichment,
    count(*) FILTER (WHERE enrichment_needed = false) AS enriched,
    count(*) AS total
   FROM pipeline_runs;
REVOKE ALL ON public.dashboard_enrichment FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_enrichment TO anon;
GRANT SELECT ON public.dashboard_enrichment TO authenticated;

CREATE VIEW public.dashboard_error_health AS
 SELECT phase,
    node_name,
    count(*) AS errors,
    count(*) FILTER (WHERE NOT resolved) AS unresolved
   FROM pipeline_errors
  GROUP BY phase, node_name;
REVOKE ALL ON public.dashboard_error_health FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_error_health TO anon;
GRANT SELECT ON public.dashboard_error_health TO authenticated;

CREATE VIEW public.dashboard_hypothesis_winrate AS
 SELECT a.action_type,
    count(o.id) AS measured,
    count(o.id) FILTER (WHERE o.result = 'met'::text) AS met,
    round(100.0 * count(o.id) FILTER (WHERE o.result = 'met'::text)::numeric / NULLIF(count(o.id), 0)::numeric, 0) AS win_rate_pct
   FROM actions a
     LEFT JOIN outcomes o ON o.action_id = a.id
  GROUP BY a.action_type;
REVOKE ALL ON public.dashboard_hypothesis_winrate FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_hypothesis_winrate TO anon;
GRANT SELECT ON public.dashboard_hypothesis_winrate TO authenticated;

CREATE VIEW public.dashboard_kpis AS
 SELECT count(*) AS total,
    count(*) FILTER (WHERE brief_generated) AS briefs_generated,
    count(*) FILTER (WHERE human_approved) AS approved
   FROM pipeline_runs;
REVOKE ALL ON public.dashboard_kpis FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_kpis TO anon;
GRANT SELECT ON public.dashboard_kpis TO authenticated;

CREATE VIEW public.dashboard_mmm_readiness AS
 WITH chan AS (
         SELECT o_1.funnel_stage,
            count(DISTINCT a.action_type) AS channels_used
           FROM campaign_objectives o_1
             JOIN actions a ON a.campaign_id = o_1.campaign_id AND (a.status = ANY (ARRAY['executed'::text, 'measured'::text]))
          GROUP BY o_1.funnel_stage
        )
 SELECT fs.key AS funnel_stage,
    fs.label,
    fs.sort_order,
    count(o.status) AS objectives_total,
    count(*) FILTER (WHERE o.status = 'met'::text) AS met,
    count(*) FILTER (WHERE o.status = 'missed'::text) AS missed,
    count(*) FILTER (WHERE o.status = 'open'::text) AS open,
    count(*) FILTER (WHERE o.status = ANY (ARRAY['met'::text, 'missed'::text])) AS labeled_rows,
    COALESCE(max(chan.channels_used), 0::bigint) AS channels_used,
    GREATEST(30::bigint, 10 * COALESCE(max(chan.channels_used), 0::bigint)) AS target_rows,
    LEAST(100::numeric, round(100.0 * count(*) FILTER (WHERE o.status = ANY (ARRAY['met'::text, 'missed'::text]))::numeric / GREATEST(30::bigint, 10 * COALESCE(max(chan.channels_used), 0::bigint))::numeric)) AS readiness_pct
   FROM funnel_stages fs
     LEFT JOIN campaign_objectives o ON o.funnel_stage = fs.key
     LEFT JOIN chan ON chan.funnel_stage = fs.key
  GROUP BY fs.key, fs.label, fs.sort_order;
REVOKE ALL ON public.dashboard_mmm_readiness FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_mmm_readiness TO anon;
GRANT SELECT ON public.dashboard_mmm_readiness TO authenticated;

CREATE VIEW public.dashboard_rejection_reasons AS
 SELECT COALESCE(rejection_reason, '(unspecified)'::text) AS label,
    COALESCE(rejection_routed_to, '—'::text) AS routed_to,
    count(*) AS n
   FROM actions
  WHERE status = 'cancelled'::text
  GROUP BY rejection_reason, rejection_routed_to
  ORDER BY (count(*)) DESC;
REVOKE ALL ON public.dashboard_rejection_reasons FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_rejection_reasons TO anon;
GRANT SELECT ON public.dashboard_rejection_reasons TO authenticated;

CREATE VIEW public.dashboard_top_accounts AS
 SELECT account,
    score,
    engagement_events,
    last_event,
    hard_points,
    soft_points
   FROM account_score
  ORDER BY score DESC, engagement_events DESC
 LIMIT 15;
REVOKE ALL ON public.dashboard_top_accounts FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_top_accounts TO anon;
GRANT SELECT ON public.dashboard_top_accounts TO authenticated;

CREATE VIEW public.dashboard_trend AS
 SELECT date_trunc('day'::text, (run_at AT TIME ZONE 'Asia/Singapore'::text)) AS day,
    count(*) AS n
   FROM pipeline_runs
  GROUP BY (date_trunc('day'::text, (run_at AT TIME ZONE 'Asia/Singapore'::text)))
  ORDER BY (date_trunc('day'::text, (run_at AT TIME ZONE 'Asia/Singapore'::text)));
REVOKE ALL ON public.dashboard_trend FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_trend TO anon;
GRANT SELECT ON public.dashboard_trend TO authenticated;

CREATE VIEW public.dashboard_trigger_type AS
 SELECT
        CASE
            WHEN trigger_type IS NULL OR (TRIM(BOTH FROM trigger_type) = ANY (ARRAY[''::text, ':'::text])) THEN 'Unknown'::text
            ELSE split_part(trigger_type, ':'::text, 1)
        END AS label,
    count(*) AS n
   FROM pipeline_runs
  GROUP BY (
        CASE
            WHEN trigger_type IS NULL OR (TRIM(BOTH FROM trigger_type) = ANY (ARRAY[''::text, ':'::text])) THEN 'Unknown'::text
            ELSE split_part(trigger_type, ':'::text, 1)
        END);
REVOKE ALL ON public.dashboard_trigger_type FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.dashboard_trigger_type TO anon;
GRANT SELECT ON public.dashboard_trigger_type TO authenticated;

CREATE VIEW public.feedback_for_engine_logic AS
 SELECT id,
    account,
    action_type,
    rejection_reason,
    decided_at
   FROM actions
  WHERE status = 'cancelled'::text AND rejection_routed_to = 'engine_logic'::text
  ORDER BY decided_at DESC;
REVOKE ALL ON public.feedback_for_engine_logic FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.feedback_for_engine_logic TO anon;
GRANT SELECT ON public.feedback_for_engine_logic TO authenticated;

CREATE VIEW public.feedback_for_source AS
 SELECT id,
    account,
    action_type,
    rejection_reason,
    decided_at
   FROM actions
  WHERE status = 'cancelled'::text AND rejection_routed_to = 'source'::text
  ORDER BY decided_at DESC;
REVOKE ALL ON public.feedback_for_source FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.feedback_for_source TO anon;
GRANT SELECT ON public.feedback_for_source TO authenticated;

CREATE VIEW public.mmm_account_action_mix AS
 WITH acts AS (
         SELECT a.campaign_id,
            a.account,
            count(*) FILTER (WHERE a.action_type = 'email'::text) AS n_email,
            count(*) FILTER (WHERE a.action_type = 'linkedin_connect'::text) AS n_linkedin_connect,
            count(*) FILTER (WHERE a.action_type = 'linkedin_engage'::text) AS n_linkedin_engage,
            count(*) FILTER (WHERE a.action_type = 'invite'::text) AS n_invite,
            count(*) FILTER (WHERE a.action_type = 'landing_page'::text) AS n_landing_page,
            count(*) FILTER (WHERE a.action_type = 'content_download'::text) AS n_content_download,
            count(*) FILTER (WHERE a.action_type = 'ads'::text) AS n_ads,
            count(*) FILTER (WHERE a.action_type = 'webinar'::text) AS n_webinar,
            count(*) FILTER (WHERE a.action_type = 'phone'::text) AS n_phone,
            count(*) FILTER (WHERE a.action_type = 'partner'::text) AS n_partner,
            count(*) AS total_touches,
            count(DISTINCT a.action_type) AS distinct_channels,
            min(a.executed_at) AS first_touch_at,
            max(a.executed_at) AS last_touch_at
           FROM actions a
          WHERE a.status = ANY (ARRAY['executed'::text, 'measured'::text])
          GROUP BY a.campaign_id, a.account
        )
 SELECT m.campaign_id,
    m.account,
    o.id AS objective_id,
    o.funnel_stage,
    o.objective_key,
    c.template_key,
    m.n_email,
    m.n_linkedin_connect,
    m.n_linkedin_engage,
    m.n_invite,
    m.n_landing_page,
    m.n_content_download,
    m.n_ads,
    m.n_webinar,
    m.n_phone,
    m.n_partner,
    m.total_touches,
    m.distinct_channels,
    round(EXTRACT(epoch FROM m.last_touch_at - m.first_touch_at) / 86400.0, 2) AS touch_span_days,
    s.hard_points,
    s.soft_points,
    COALESCE(o.status = 'met'::text, false) AS objective_met,
    o.target_value,
    o.window_days,
    o.status AS objective_status
   FROM acts m
     JOIN campaigns c ON c.id = m.campaign_id
     LEFT JOIN campaign_objectives o ON o.campaign_id = m.campaign_id
     LEFT JOIN account_score s ON s.account = m.account;
REVOKE ALL ON public.mmm_account_action_mix FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.mmm_account_action_mix TO anon;
GRANT SELECT ON public.mmm_account_action_mix TO authenticated;

-- ============ FUNCTIONS ============
CREATE OR REPLACE FUNCTION public.set_action_client()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.client_id is null and new.campaign_id is not null then
    select client_id into new.client_id from campaigns where id = new.campaign_id;
  end if;
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.set_campaign_client()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.client_id is null and new.run_id is not null then
    select client_id into new.client_id from pipeline_runs where id = new.run_id;
  end if;
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.set_engagement_client()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.client_id is null and coalesce(new.campaign, '') <> '' then
    select a.client_id into new.client_id from actions a where a.utm_campaign = new.campaign limit 1;
  end if;
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.set_pipeline_run_client()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.client_id is null then
    new.client_id := nullif((select value from app_config where key='default_client_id'), '')::bigint;
  end if;
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.sync_cadence_step_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.status is distinct from old.status then
    update cadence_steps set status = new.status where action_id = new.id;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.update_objective_status()
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  -- MET: an open objective whose campaign/account saw a success event in-window,
  -- attributed to the campaign (via action_id or utm match).
  update campaign_objectives obj
  set status = 'met', met_at = now()
  from campaigns cc
  where obj.campaign_id = cc.id
    and obj.status = 'open'
    and exists (
      select 1 from engagement_events ev
      where ev.account = cc.account
        and ev.event_type = any(obj.success_events)
        and ev.occurred_at >= obj.created_at
        and ev.occurred_at <  obj.created_at + make_interval(days => obj.window_days)
        and (
          ev.action_id in (select id from actions where campaign_id = obj.campaign_id)
          or ev.campaign in (select utm_campaign from actions where campaign_id = obj.campaign_id and utm_campaign is not null)
        )
    );

  -- MISSED: open objectives whose window has fully closed with no success.
  update campaign_objectives obj
  set status = 'missed'
  from campaigns cc
  where obj.campaign_id = cc.id
    and obj.status = 'open'
    and now() >= obj.created_at + make_interval(days => obj.window_days);
end;
$function$;

-- ============ TRIGGERS ============
CREATE TRIGGER trg_actions_client BEFORE INSERT ON public.actions FOR EACH ROW EXECUTE FUNCTION set_action_client();
CREATE TRIGGER trg_sync_cadence_step_status AFTER UPDATE ON public.actions FOR EACH ROW EXECUTE FUNCTION sync_cadence_step_status();
CREATE TRIGGER trg_campaigns_client BEFORE INSERT ON public.campaigns FOR EACH ROW EXECUTE FUNCTION set_campaign_client();
CREATE TRIGGER trg_engagement_client BEFORE INSERT ON public.engagement_events FOR EACH ROW EXECUTE FUNCTION set_engagement_client();
CREATE TRIGGER trg_pipeline_runs_client BEFORE INSERT ON public.pipeline_runs FOR EACH ROW EXECUTE FUNCTION set_pipeline_run_client();

-- ============ SEED DATA ============
-- NOTE (multi-client layer, added ~2026-07-10): create your clients row and point
-- app_config.default_client_id at it, e.g.:
--   insert into clients (name, rep_email) values ('Design Prodigy', 'rep@dp.sg') returning id;
--   update app_config set value='<that id>' where key='default_client_id';
-- funnel_stages
INSERT INTO public.funnel_stages (key, label, sort_order, description) VALUES
  ('cold', 'Cold / Unaware', 10, 'No prior engagement; objective is a first micro-response ("entice the cold")'),
  ('aware', 'Aware / Early', 20, 'Low-intent, early-awareness; nurture with content'),
  ('engaged', 'Engaged', 30, 'Repeated signals; warm but not yet sales-ready'),
  ('qualified', 'Qualified / Intent', 40, 'Clear buying signal; push for reply / meeting'),
  ('opportunity', 'Opportunity', 50, 'Meeting / opportunity created; sales-led'),
  ('customer', 'Customer (expand)', 60, 'Existing customer: renewal / expansion / cross-sell')
ON CONFLICT DO NOTHING;

-- action_channels
INSERT INTO public.action_channels (key, label, description, is_high_touch, sort_order) VALUES
  ('email', 'Email', 'Direct email with a tracked link', false, 10),
  ('linkedin_engage', 'LinkedIn Engage', 'Like/comment on the contact''s content to warm them up', false, 20),
  ('content_download', 'Content Download', 'Share a gated asset (guide, whitepaper) via tracked link', false, 30),
  ('landing_page', 'Landing Page', 'Send a tracked landing-page link', false, 40),
  ('ads', 'Ads', 'Paid retargeting / display against the account', false, 50),
  ('webinar', 'Webinar', 'Invite to, or follow up on, a webinar', false, 60),
  ('invite', 'Event / Meeting Invite', 'Direct invite to an event or meeting', true, 70),
  ('linkedin_connect', 'LinkedIn Connect', 'Connection request to a buying-group contact', true, 80),
  ('phone', 'Phone Call', 'Direct outbound call', true, 90),
  ('partner', 'Partner Intro', 'Warm introduction via an ecosystem partner', true, 100)
ON CONFLICT DO NOTHING;

-- campaign_templates (18 playbooks incl. objectives + funnel stages)
INSERT INTO public.campaign_templates (key, name, description, match_urgency_in, match_coverage_in, match_stage_contains, priority, steps, match_keywords, goal, kpi_metric, kpi_target, funnel_stage, objective_success_events, objective_target_value, objective_window_days) VALUES
  ('abm', 'ABM (Named Account, Broad Coverage)', 'Full buying-group coverage on a named account — multi-thread rather than single-thread.', NULL, '{"BROAD"}'::text[], NULL, 18, '[{"reason": "Connect with each confirmed buying-group member in parallel.", "delay_days": 0, "action_type": "linkedin_connect"}, {"reason": "Send a tailored note to the primary stakeholder.", "delay_days": 2, "action_type": "email"}, {"reason": "Engage across the buying group to stay visible to all threads.", "delay_days": 5, "action_type": "linkedin_engage"}, {"reason": "Run account-targeted retargeting while multi-threading the buying group.", "delay_days": 7, "action_type": "ads"}, {"reason": "Call the primary stakeholder to consolidate the multi-thread into a meeting.", "delay_days": 10, "action_type": "phone"}, {"reason": "Recap with the full buying group and propose next steps.", "delay_days": 16, "action_type": "email"}]'::jsonb, NULL, 'Multi-thread the full buying group on a named account before single-threaded competitors do', 'reply_or_meeting', '2+ stakeholder replies within 21 days', 'qualified', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 2, 21),
  ('cold_outreach', 'Cold outreach', 'Cold-stage account — open the relationship gradually before asking for anything.', NULL, NULL, 'COLD', 20, '[{"reason": "Lowest-friction first touch \u2014 open the relationship", "delay_days": 0, "action_type": "linkedin_connect"}, {"reason": "Warm them via likes/comments on recent posts", "delay_days": 2, "action_type": "linkedin_engage"}, {"reason": "Lead with the strategic angle", "delay_days": 5, "action_type": "email"}, {"reason": "Offer a gated asset to gauge intent", "delay_days": 7, "action_type": "content_download"}, {"reason": "Easier ask than a sales call", "delay_days": 10, "action_type": "invite"}]'::jsonb, NULL, 'Establish initial contact and qualify interest on a cold-stage account', 'reply_or_meeting', '1 response within 21 days', 'cold', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 21),
  ('competitive_replacement', 'Competitive Replacement', 'Account is actively evaluating or being approached about replacing an incumbent vendor.', NULL, NULL, NULL, 11, '[{"reason": "Open with the competitive displacement angle \u2014 name the gap in their current vendor and a concrete head-to-head comparison.", "delay_days": 0, "action_type": "email"}, {"reason": "Engage with their recent activity to stay visible while the comparison lands.", "delay_days": 2, "action_type": "linkedin_engage"}, {"reason": "Send the competitive comparison sheet.", "delay_days": 4, "action_type": "content_download"}, {"reason": "Call to push for a meeting before they renew with the incumbent.", "delay_days": 7, "action_type": "phone"}, {"reason": "Final follow-up referencing the comparison sheet and a renewal-timeline question.", "delay_days": 10, "action_type": "email"}]'::jsonb, '{"competitor", "displace", "displacement", "rival", "switch from", "incumbent", "rip and replace"}'::text[], 'Win a head-to-head displacement before the incumbent renews', 'reply_or_meeting', '1 meeting booked within 14 days', 'qualified', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 14),
  ('conference_followup', 'Conference Follow-up', 'Account was sourced from or engaged at a conference, summit, or trade show.', NULL, NULL, NULL, 16, '[{"reason": "Reference the specific conversation or booth visit while it is still fresh.", "delay_days": 0, "action_type": "email"}, {"reason": "Connect on LinkedIn right after the event.", "delay_days": 1, "action_type": "linkedin_connect"}, {"reason": "Send the resource they asked about at the event.", "delay_days": 3, "action_type": "content_download"}, {"reason": "Call to lock in a follow-up meeting before the post-event window closes.", "delay_days": 5, "action_type": "phone"}]'::jsonb, '{"conference", "summit", "expo", "trade show", "booth", "attended"}'::text[], 'Convert a fresh event touchpoint into a meeting while the conversation is still warm', 'reply_or_meeting', '1 meeting booked within 7 days', 'engaged', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 7),
  ('cross_sell', 'Cross-Sell', 'Existing account showing signals for an adjacent product line.', NULL, NULL, NULL, 21, '[{"reason": "Introduce the adjacent product line relevant to their current usage.", "delay_days": 0, "action_type": "email"}, {"reason": "Stay visible while they consider the adjacent offering.", "delay_days": 4, "action_type": "linkedin_engage"}, {"reason": "Share a case study on the adjacent product.", "delay_days": 7, "action_type": "content_download"}, {"reason": "Call to scope a cross-sell conversation.", "delay_days": 12, "action_type": "phone"}]'::jsonb, '{"cross-sell", "cross sell", "also use", "adjacent product", "additional license"}'::text[], 'Expand footprint into an adjacent product line within an existing account', 'reply_or_meeting', '1 meeting booked within 21 days', 'customer', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 21),
  ('customer_success', 'Customer Success Check-in', 'Existing account with an adoption or health-risk signal worth a proactive touch.', NULL, NULL, NULL, 24, '[{"reason": "Proactively check in on the adoption or health signal.", "delay_days": 0, "action_type": "email"}, {"reason": "Call to understand the root cause and offer help.", "delay_days": 3, "action_type": "phone"}, {"reason": "Stay visible during the check-in period.", "delay_days": 6, "action_type": "linkedin_engage"}]'::jsonb, '{"customer success", "health check", "renewal risk", "low adoption", "onboarding"}'::text[], 'Proactively address an adoption or health-risk signal before it becomes churn', 'reply_or_meeting', '1 meeting booked within 14 days', 'customer', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 14),
  ('dormant_account', 'Dormant Account', 'Previously-engaged account that has gone quiet.', NULL, NULL, NULL, 30, '[{"reason": "Light-touch check-in referencing the prior engagement.", "delay_days": 0, "action_type": "email"}, {"reason": "Re-engage gently on LinkedIn.", "delay_days": 5, "action_type": "linkedin_engage"}, {"reason": "Share new content relevant to what they cared about before.", "delay_days": 10, "action_type": "content_download"}]'::jsonb, '{"dormant", "gone quiet", "previously engaged", "no recent activity"}'::text[], 'Surface a previously-engaged account that has gone quiet before writing them off', 'reply_or_meeting', '1 response within 21 days', 'engaged', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 21),
  ('executive_event', 'Executive Event / Leadership Change', 'A new executive has joined or a leadership change creates a fresh window of opportunity.', NULL, NULL, NULL, 12, '[{"reason": "Connect with the new executive directly.", "delay_days": 0, "action_type": "linkedin_connect"}, {"reason": "Congratulate on the new role and tie our catch to their likely first-90-days priorities.", "delay_days": 3, "action_type": "email"}, {"reason": "Stay visible while they settle into the role.", "delay_days": 6, "action_type": "linkedin_engage"}, {"reason": "Call to get on the calendar before their plan is finalized.", "delay_days": 10, "action_type": "phone"}, {"reason": "Final nudge referencing any public statements they have made since starting.", "delay_days": 14, "action_type": "email"}]'::jsonb, '{"leadership change", "new ceo", "new cto", "new cfo", "new coo", "executive appointment", "interim appointed", "executive change"}'::text[], 'Build a relationship with the new executive before their first-90-days plan is set', 'reply_or_meeting', '1 meeting booked within 21 days', 'engaged', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 21),
  ('expansion', 'Expansion', 'Existing account showing usage growth signals worth expanding.', NULL, NULL, NULL, 23, '[{"reason": "Flag the usage growth and propose an expanded plan.", "delay_days": 0, "action_type": "email"}, {"reason": "Stay visible while they consider expanding.", "delay_days": 3, "action_type": "linkedin_engage"}, {"reason": "Call to scope the expansion.", "delay_days": 7, "action_type": "phone"}]'::jsonb, '{"expansion", "expand usage", "scale up", "additional seats", "growing usage"}'::text[], 'Grow seat count or usage within an already-engaged account', 'reply_or_meeting', '1 meeting booked within 21 days', 'customer', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 21),
  ('narrow_coverage_nurture', 'Narrow-coverage nurture', 'Buying group contacts are unconfirmed — lower-touch, content/ad-led cadence per the coverage-routing rule.', NULL, '{"NARROW"}'::text[], NULL, 15, '[{"reason": "Offer a gated asset \u2014 no confirmed contact to message directly yet", "delay_days": 0, "action_type": "content_download"}, {"reason": "Drive traffic while enrichment is pending", "delay_days": 4, "action_type": "landing_page"}, {"reason": "Attempt to confirm a real contact via connect", "delay_days": 8, "action_type": "linkedin_connect"}, {"reason": "Only once some signal suggests a contact is reachable", "delay_days": 14, "action_type": "email"}]'::jsonb, NULL, 'Build buying-group coverage on a narrowly-covered account before pushing for a meeting', 'profile_visit', 'expand confirmed contacts to 2+ within 21 days', 'aware', '{"profile_visit", "linkedin_profile_view", "linkedin_accept"}'::text[], 2, 21),
  ('partner_campaign', 'Partner Campaign', 'Account has an active or newly announced partnership/alliance we can route through.', NULL, NULL, NULL, 14, '[{"reason": "Loop in our partner contact to make a warm introduction off the back of the announced partnership.", "delay_days": 0, "action_type": "partner"}, {"reason": "Follow the partner intro with a direct note tying our offering to the partnership.", "delay_days": 3, "action_type": "email"}, {"reason": "Connect directly in parallel with the partner-led intro.", "delay_days": 5, "action_type": "linkedin_connect"}, {"reason": "Call to convert the warm intro into a meeting.", "delay_days": 9, "action_type": "phone"}]'::jsonb, '{"partner", "partnership", "alliance", "co-sell", "collaboration"}'::text[], 'Open a co-sell or ecosystem conversation off the back of the partnership announcement', 'partner_response', '1 partner-side response within 14 days', 'aware', '{"partner_response"}'::text[], 1, 14),
  ('product_launch', 'Product Launch', 'Account just launched a new product, platform, or initiative.', NULL, NULL, NULL, 13, '[{"reason": "Congratulate on the launch and connect our capability to what they just shipped.", "delay_days": 0, "action_type": "email"}, {"reason": "Engage with their launch announcement post.", "delay_days": 2, "action_type": "linkedin_engage"}, {"reason": "Share a relevant case study or technical brief.", "delay_days": 5, "action_type": "content_download"}, {"reason": "Follow up before the next vendor evaluation cycle starts.", "delay_days": 9, "action_type": "email"}]'::jsonb, '{"product launch", "launched", "new platform", "platform announc", "unveil", "rollout", "go-live", "go live"}'::text[], 'Land early before competitors pile onto the new initiative', 'reply_or_meeting', '1 meeting booked within 14 days', 'qualified', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 14),
  ('reactivation', 'Reactivation', 'Lapsed or churned account that needs a stronger win-back push than a standard nurture.', NULL, NULL, NULL, 31, '[{"reason": "Make a direct win-back offer.", "delay_days": 0, "action_type": "email"}, {"reason": "Call to address whatever caused the lapse.", "delay_days": 4, "action_type": "phone"}, {"reason": "Reconnect on LinkedIn in parallel.", "delay_days": 7, "action_type": "linkedin_connect"}, {"reason": "Final win-back push with a concrete next step.", "delay_days": 12, "action_type": "email"}]'::jsonb, '{"reactivat", "win-back", "win back", "lapsed", "churned"}'::text[], 'Win back a lapsed account with a stronger, more direct offer than a standard nurture', 'reply_or_meeting', '1 meeting booked within 21 days', 'engaged', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 21),
  ('renewal', 'Renewal', 'Existing account approaching contract renewal.', NULL, NULL, NULL, 22, '[{"reason": "Open the renewal conversation early, ahead of the contract end date.", "delay_days": 0, "action_type": "email"}, {"reason": "Call to confirm renewal intent and surface any risk.", "delay_days": 5, "action_type": "phone"}, {"reason": "Stay visible through the renewal cycle.", "delay_days": 8, "action_type": "linkedin_engage"}, {"reason": "Follow up with renewal terms or an expansion option.", "delay_days": 14, "action_type": "email"}]'::jsonb, '{"renewal", "contract expir", "up for renewal", "renew"}'::text[], 'Lock the renewal early and head off any churn risk', 'reply_or_meeting', '1 meeting booked within 30 days of contract end', 'customer', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 30),
  ('thought_leadership', 'Thought Leadership', 'Low-intent, early-awareness contact (newsletter/content signup) not yet showing buying signals.', NULL, NULL, NULL, 85, '[{"reason": "Lead with educational content matched to their stated interest.", "delay_days": 0, "action_type": "content_download"}, {"reason": "Stay visible without a hard pitch.", "delay_days": 5, "action_type": "linkedin_engage"}, {"reason": "Share a second piece of content to build trust.", "delay_days": 12, "action_type": "content_download"}, {"reason": "Soft check-in \u2014 no hard CTA, just gauge interest.", "delay_days": 20, "action_type": "email"}]'::jsonb, '{"newsletter", "subscribed", "content syndication", "downloaded", "whitepaper signup"}'::text[], 'Nurture a low-intent, early-awareness contact with educational content until they show buying signals', 'content_download', 'sustained content engagement; re-evaluate for a harder CTA after 30 days', 'aware', '{"content_download", "email_click"}'::text[], 1, 30),
  ('urgent_fast_track', 'Urgent fast-track', 'High-urgency signal — skip the slow build, go straight for the ask.', '{"URGENT", "LIVE", "HIGH", "ACT NOW"}'::text[], NULL, NULL, 10, '[{"reason": "Lead with the urgency signal \u2014 do not wait", "delay_days": 0, "action_type": "email"}, {"reason": "Drive to a tailored account page while it is hot", "delay_days": 1, "action_type": "landing_page"}, {"reason": "Ask for the meeting directly \u2014 urgency justifies skipping content gating", "delay_days": 3, "action_type": "invite"}]'::jsonb, NULL, 'Move fast on a time-sensitive, high-urgency signal before the window closes', 'reply_or_meeting', '1 response within 7 days', 'qualified', '{"meeting_booked", "call_connected", "crm_activity", "linkedin_reply", "email_reply"}'::text[], 1, 7),
  ('warm_reengage', 'Nurture (Warm Re-engage)', 'Default cadence for an already-warm, decently-covered account that is not yet ready to buy. Fallback template — matches everything not caught above.', NULL, NULL, NULL, 99, '[{"reason": "Re-engage an already-warm contact", "delay_days": 0, "action_type": "linkedin_engage"}, {"reason": "Go direct for a meeting", "delay_days": 2, "action_type": "email"}, {"reason": "Drive to a tailored account page", "delay_days": 5, "action_type": "landing_page"}, {"reason": "Offer a gated asset (e.g. sector guide)", "delay_days": 7, "action_type": "content_download"}, {"reason": "Offer a roundtable as a soft next step", "delay_days": 10, "action_type": "invite"}]'::jsonb, NULL, 'Keep a warm-but-not-yet-ready account engaged until a stronger buying signal appears', 'profile_visit', 'sustained engagement; re-evaluate in 30 days', 'engaged', '{"profile_visit", "linkedin_profile_view", "linkedin_accept", "linkedin_post_engage"}'::text[], 1, 30),
  ('webinar', 'Webinar', 'Account registered for or attended a webinar.', NULL, NULL, NULL, 17, '[{"reason": "Invite to the related or next webinar session, or send the recording.", "delay_days": 0, "action_type": "webinar"}, {"reason": "Follow up on what they registered for and offer a related resource.", "delay_days": 2, "action_type": "email"}, {"reason": "Engage with their profile to stay visible.", "delay_days": 4, "action_type": "linkedin_engage"}, {"reason": "Share related content to keep them engaged toward a meeting.", "delay_days": 7, "action_type": "content_download"}]'::jsonb, '{"webinar", "registered for", "signed up for", "online event"}'::text[], 'Turn a webinar registration into a qualified follow-on conversation', 'registration', '1 follow-on meeting within 10 days', 'engaged', '{"registration"}'::text[], 1, 10)
ON CONFLICT DO NOTHING;

-- heartbeat_expected (Pipeline Heartbeat registry)
INSERT INTO public.heartbeat_expected (workflow_id, name, kind, max_silence_hours, enabled, note) VALUES
  ('UyplqAAHgTNOvRuC', 'Action Approval Handler', 'webhook', NULL, true, NULL),
  ('RMPUPcf2o0ltJVeG', 'Action Outcome Measurement', 'schedule', 26, true, NULL),
  ('tGYW1gMBXQrC3bQ6', 'Adaptive Decision Engine', 'schedule', 26, true, NULL),
  ('AoVkLOncTxZqQlwz', 'Brief Approval Handler', 'webhook', NULL, true, NULL),
  ('LcZx5U9dVmOwaGQl', 'Cadence Scheduler', 'schedule', 26, true, NULL),
  ('VLmJHUXyuvHVXdI7', 'Calendly -> Engagement (meetings)', 'webhook', NULL, true, NULL),
  ('sTU9hQDkVWzveVzx', 'Client Onboarding', 'webhook', NULL, true, 'added 2026-07-09'),
  ('mw2KJ3AOea9rhSDT', 'Digest Approve All', 'webhook', NULL, true, NULL),
  ('cipD4rUtuzYeiHan', 'Digest Reply Logger', 'schedule', 2, true, 'added 2026-07-11; every 30 min'),
  ('V9Ywv5lW6eZ7qY5h', 'Draft Backfill', 'schedule', 6, true, 'runs every 2h; 6h = 3 missed ticks'),
  ('2vvJUpNgJwGtLjPy', 'Draft Generator', 'webhook', NULL, true, NULL),
  ('hAQ1e1DpFkgUBjwc', 'Email Events -> Engagement', 'webhook', NULL, true, NULL),
  ('grv4TN8pUrrW0xPa', 'Engagement -> WHEN Signals', 'schedule', 26, true, NULL),
  ('fsPZuAbWdQb16kXm', 'Engagement Ingest', 'webhook', NULL, true, NULL),
  ('20tIbI4ku7j35dma', 'GA4 -> Engagement Feeder', 'schedule', 26, true, NULL),
  ('HQdvWtRfLdzDTN3X', 'Intelligent Automation — Delivery Layer', 'webhook', NULL, true, NULL),
  ('pGMO2FUg1tHpbwsR', 'LinkedIn -> Engagement', 'webhook', NULL, true, NULL),
  ('B5XMs4A7UcrE3iCy', 'LinkedIn Post Approval Handler', 'webhook', NULL, true, NULL),
  ('Tz9PbNnFG1KRWHqK', 'LinkedIn Post Generator', 'webhook', NULL, true, NULL),
  ('er7QvTbfSkyc60wx', 'Opportunity Approval Handler', 'webhook', NULL, true, NULL),
  ('dnGpK2weiPIcikGa', 'Opportunity Offer', 'schedule', 26, true, NULL),
  ('MJHuNccpX2QURdBe', 'pg_cron Failure Alert', 'schedule', 26, true, NULL),
  ('LBJutargTXG3qsIN', 'Pre-Meeting Prep', 'schedule', 2, true, 'added 2026-07-11; every 15 min'),
  ('qYkwb4h5riveVwNJ', 'Recommendation Expiry', 'schedule', 26, true, NULL),
  ('MasoBylwk6R2i0EI', 'Reply Triage', 'schedule', 3, true, 'added 2026-07-10; hourly at :20'),
  ('mL0H9QHe73SouLsR', 'Salesforce Activities Read-back', 'schedule', 26, true, NULL),
  ('PZThZtvGakw82RX8', 'Salesforce Task Outcome Sync', 'schedule', 26, true, NULL),
  ('a8q9lmLVIxahPCTk', 'Sign Link', 'webhook', NULL, true, 'the 2026-07-01 silent-deactivation incident this heartbeat exists for'),
  ('KceyHKozWt7dTwGR', 'Stale Touch Nudge', 'schedule', 26, true, 'added 2026-07-11; daily 08:00 UTC'),
  ('OoO1O8UKiYwfz5SK', 'Tool Campaign Provisioner', 'schedule', 26, true, 'added 2026-07-09; no-op while smartlead_api_key blank'),
  ('kA9tQQe4tsFTjbhu', 'Weekly Wins Report', 'schedule', 192, true, 'added 2026-07-11; Fridays 01:00 UTC — 8-day window')
ON CONFLICT DO NOTHING;

-- app_config — secrets BLANKED; set approval_hmac_secret on the new project:
--   update app_config set value = encode(gen_random_bytes(32),'hex') where key='approval_hmac_secret';
-- The default client that every untagged brief falls to (gets id 1 on a fresh database;
-- app_config.default_client_id below assumes it). Update rep_email after install if needed.
INSERT INTO public.clients (name, rep_email) VALUES
  ('Design Prodigy (house)', 'chiahonlam.school@gmail.com')
ON CONFLICT DO NOTHING;

INSERT INTO public.app_config (key, value) VALUES
  ('approval_hmac_secret', ''),
  ('approval_required_channels', 'phone,partner'),
  ('default_client_id', '1'),
  ('ga4_property_id', '542471069'),
  ('heyreach_api_key', ''),
  ('manager_report_email', 'chiahonlam.school@gmail.com'),
  ('onboarding_code', encode(gen_random_bytes(6), 'hex')),  -- fresh secret per install (never commit a real one)
  ('recommendation_expiry_days', '7'),
  ('rep_notification_email', 'chiahonlam.school@gmail.com'),
  ('smartlead_api_key', ''),
  ('tracking_base_url', 'http://www.dp.sg'),
  ('when_engine_url', ''),
  ('channel_explore_enabled', 'false'),
  ('channel_explore_epsilon', '0.2')
ON CONFLICT DO NOTHING;

-- ============ MMM: explore-only matrix + fitted-effects table ============
-- Added 2026-07-23. These were created live but were originally missing from
-- this bootstrap, which made the re-home incomplete (the MMM tab 404'd on
-- mmm_channel_effects). Standalone migrations: supabase/2026-07-22_mmm_explore_matrix.sql
-- and supabase/2026-07-23_mmm_channel_effects_table.sql.

-- Explore-only matrix: same as mmm_account_action_mix but counting ONLY
-- randomized exploration touches (channel_source='explore') for a causal fit.
CREATE OR REPLACE VIEW public.mmm_account_action_mix_explore AS
 WITH acts AS (
   SELECT a.campaign_id,
          a.account,
          count(*) FILTER (WHERE a.action_type = 'email'::text)            AS n_email,
          count(*) FILTER (WHERE a.action_type = 'linkedin_connect'::text) AS n_linkedin_connect,
          count(*) FILTER (WHERE a.action_type = 'linkedin_engage'::text)  AS n_linkedin_engage,
          count(*) FILTER (WHERE a.action_type = 'invite'::text)           AS n_invite,
          count(*) FILTER (WHERE a.action_type = 'landing_page'::text)     AS n_landing_page,
          count(*) FILTER (WHERE a.action_type = 'content_download'::text) AS n_content_download,
          count(*) FILTER (WHERE a.action_type = 'ads'::text)              AS n_ads,
          count(*) FILTER (WHERE a.action_type = 'webinar'::text)          AS n_webinar,
          count(*) FILTER (WHERE a.action_type = 'phone'::text)            AS n_phone,
          count(*) FILTER (WHERE a.action_type = 'partner'::text)          AS n_partner,
          count(*)                        AS total_touches,
          count(DISTINCT a.action_type)   AS distinct_channels,
          min(a.executed_at)              AS first_touch_at,
          max(a.executed_at)              AS last_touch_at
     FROM actions a
    WHERE a.status = ANY (ARRAY['executed'::text, 'measured'::text])
      AND a.channel_source = 'explore'::text
    GROUP BY a.campaign_id, a.account
 )
 SELECT m.campaign_id, m.account, o.id AS objective_id, o.funnel_stage, o.objective_key, c.template_key,
        m.n_email, m.n_linkedin_connect, m.n_linkedin_engage, m.n_invite,
        m.n_landing_page, m.n_content_download, m.n_ads, m.n_webinar, m.n_phone, m.n_partner,
        m.total_touches, m.distinct_channels,
        round(EXTRACT(epoch FROM m.last_touch_at - m.first_touch_at) / 86400.0, 2) AS touch_span_days,
        s.hard_points, s.soft_points,
        COALESCE(o.status = 'met'::text, false) AS objective_met,
        o.target_value, o.window_days, o.status AS objective_status
   FROM acts m
   JOIN campaigns c              ON c.id = m.campaign_id
   LEFT JOIN campaign_objectives o ON o.campaign_id = m.campaign_id
   LEFT JOIN account_score s     ON s.account = m.account;
REVOKE ALL ON public.mmm_account_action_mix_explore FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.mmm_account_action_mix_explore TO anon, authenticated;

-- Fitted per-stage channel odds ratios written by mmm/mmm_regression.py --db-write,
-- read directly by the dashboards' MMM tab (anon).
CREATE TABLE IF NOT EXISTS public.mmm_channel_effects (
  funnel_stage text        NOT NULL,
  channel      text        NOT NULL,
  odds_ratio   double precision,
  ci_low       double precision,
  ci_high      double precision,
  p_value      double precision,
  significant  boolean,
  method       text,
  labeled_rows integer,
  computed_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.mmm_channel_effects ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mmm_channel_effects FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.mmm_channel_effects TO anon, authenticated;
DROP POLICY IF EXISTS mmm_channel_effects_read ON public.mmm_channel_effects;
CREATE POLICY mmm_channel_effects_read ON public.mmm_channel_effects
  FOR SELECT TO anon, authenticated USING (true);

-- ============ SCHEDULED JOB (pg_cron) ============
DO $$ BEGIN
  PERFORM cron.schedule('objective-status-daily', '30 7 * * *', 'select public.update_objective_status();');
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pg_cron not available — schedule objective-status-daily manually';
END $$;
